### ISSUE TITLE
Plot/glyph alignment

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#1010]
Often what you see on charticulator editor is not what will be presented out of edit mode.
Here is an example:
In edit mode, the background image and the two plots align perfectly:
![image](https://user-images.githubusercontent.com/19476550/172816886-8b60e4cb-e522-4964-a504-ced386923ac1.png)

but in power bi the image is and the bars are smaller? 
2020 for example looks like does not have any data out of edit mode.
![image](https://user-images.githubusercontent.com/19476550/172817086-e4c8765f-a475-4345-83eb-a60cee5da420.png)

Am I doing something wrong or is this the way it works and can it be prevented.
Thanks

**Comment by PBI-David** [comment]
Have you made sure your chart size in Charticulator matches the size of the visual?

**Comment by ruthpozuelo** [comment]
I see now that the size of the image will be correct if I make the viz smaller, so the image is not resizing beyond it size, I suppose? 
I will leave this here in case others wonder too but close the issue. Thanks @PBIdavid
