### ISSUE TITLE
Setting color to None won't apply upon save

### ISSUE THREAD

**Issue by kolky001** [microsoft/charticulator#1015]
**Describe the bug**
Changing some category colors to "None", appears to work. Once the chart is saved, the colors for those categories revert to default. When changing colors to "None", I expect these to be transparent.

**To Reproduce**
1. Draw Mark
3. Change Mark Fill to None
4. See the Mark has become transparent on Main Canvas
5. Save Chart
6. Color reverts to default

**Screenshots**
![image](https://user-images.githubusercontent.com/36867587/175816696-7785ae1b-3065-41e3-9cd8-47abe3203b09.png)

**Comment by zBritva** [comment]
Did you enable the color updating settings in the visual format panel?:

![image](https://user-images.githubusercontent.com/10897951/175905376-27beda04-c9eb-4b02-a197-792707e14f9d.png)

**Comment by kolky001** [comment]
Hi, No I didn't. But I just tested and the same behaviour happens enabled or not enabled.

**Comment by zBritva** [comment]
Uncheck `Auto update values`. Charticulator considers `null` for colors as new value in dataset and assigns color from Power BI palette.

**Comment by kolky001** [comment]
Where is auto-update values?
