### ISSUE TITLE
Charticulator - PowerBI export option after build

### ISSUE THREAD

**Issue by SDAravind** [microsoft/charticulator#1034]
I don't see Power BI export option after build. Is there any extension to be loaded?

![charticulator-pbi-export](https://user-images.githubusercontent.com/72403396/182756187-04adb8aa-2de4-4505-9ebd-408172b32809.png)

**Comment by zBritva** [comment]
You need install extension
https://github.com/microsoft/charticulator-extensions

**Comment by SDAravind** [comment]
Thank you
