### ISSUE TITLE
Limit to the number of glyphs I can have in my visual

### ISSUE THREAD

**Issue by Dwil1** [microsoft/charticulator#1053]
I am using Charticulator on the web and can't seem to find a way to add more than 3 glyphs to my visual. When I watched the tutorial, I could see that the presenter had the option to add additional glyphs after 3.

Do you know if there is a way I can switch this one?

![image](https://user-images.githubusercontent.com/118722257/203078355-c7f24d1b-707b-4c2e-be1a-331b669be16c.png)

**Comment by Dwil1** [comment]
Sorry I figured it out by resizing the window :)

**Comment by zBritva** [comment]
Another option is

![image](https://user-images.githubusercontent.com/10897951/203079232-b893a139-c5e6-4637-8180-d784d60b7f05.png)

**Comment by Dwil1** [comment]
Thank you!
