### ISSUE TITLE
Negative values

### ISSUE THREAD

**Issue by AlbertoTemporal** [Microsoft/charticulator#110]
Dear Sirs, 
I can not re-create a chart like "Microsoft Stock Price 1987 - 2018". 
The chart do not show the negatives as negative. 

![image](https://user-images.githubusercontent.com/44785448/48022631-f5ebee00-e13b-11e8-8767-d4eebaa6da03.png)

I here send my data: 

mes,Incremento,Reduccion,Neto,Valor 
1,32,-20,12,512
2,50,-10,40,552
3,100,-12,88,640
4,65,-15,50,690
5,32,-8,24,714
6,67,-21,46,760
7,87,-60,27,787
8,54,-32,22,809
9,20,-60,-40,769
10,23,-76,-53,716
11,55,-98,-43,673
12,33,12,45,718

**Comment by donghaoren** [comment]
Could you try setting "Start" to 0? The way it works is to map the domain [start, end] to the range [start, end], so if you set both starts to 0, negatives should appear correctly.

**Comment by donghaoren** [comment]
You can press the "Add Legend" button, the legend for a numerical scale is an axis.

**Comment by bongshin** [comment]
I'm closing this issue because there is no further discussion.

**Comment by AlbertoTemporal** [comment]
Thank so much for your follow-up !!!

Yes, the issue is closed.

Best whishes and success for next year.

Alberto
