### ISSUE TITLE
option to add a filter 

### ISSUE THREAD

**Issue by djouallah** [microsoft/charticulator#117]
it will be great if we can add a filter on the visual, so when we export to HTML, the user can filter the chart, it will open all kind of interesting scenarios. 

thanks for the great works so far

**Comment by digital-mining1** [comment]
@djouallah, can you please elaborate on this issue. It is not clear.

**Comment by djouallah** [comment]
all good, I misunderstood the purpose of the software, my request does not make sense really, I am closing the issue
