### ISSUE TITLE
Please provide a sample dataset with examples

### ISSUE THREAD

**Issue by falconair** [microsoft/charticulator#121]
Can you please provide a sample dataset with examples. This will help us validate if the error is in the way we are using the software or a bug in the code.

For example, I made a chord diagram when this software was newly released. Since then, I've done a couple of git pulls with slightly different data and can no longer generate any chart with links in it. This may mean that closed tickets (#90) represent bugs which still exist!

I don't know if I'm using the software wrong (there are some very slight differences in the video vs what I see when I follow the steps), perhaps my data is bad (cycles in the graph or misspelled nodes) or there could be a bug introduced.

Having a sample file will help narrow the issue and reproduce bugs more easily.

**Comment by bongshin** [comment]
Sorry, but we’re advised not to distribute the sample datasets.

**Comment by jeremy82many** [comment]
I am new to using the software. The video tutorials are okay, but without sample datasets, I can't figure out at all how to correctly create the link files. Can you at least make a video showing how to take a long format file and then identify the necessary pieces to get a good link file? Or whatever it is called...Advised not to distribute datasets from other people is fine, but please make your own example at least!

**Comment by digital-mining1** [comment]
@falconair and @jeremy82many In my experience, the links work fine. Just remember that the DataFile.csv should have a column called 'id' and the LinksFile.csv should have at least 2 columns called 'source_id' and 'target_id'. I suggest starting with a very simple set of data e.g. each of these 2 tables containing just 3 rows each of data. Then get the links working. And then add more data.  If you like, I can send or post sample files containing just a few rows of data.
