### ISSUE TITLE
Control over Data type

### ISSUE THREAD

**Issue by snapper911T** [microsoft/charticulator#129]
It would be beneficial to have the ability to change the data type for each field in Charticulator. Right now it seems like Charticulator automatically detects and assigns a data type which dictates how its handled within. For example if i wanted a field with "year" to be treated as numerical instead of categorical or vice versa. Another example is binning a "revenue" field to create a histogram. My X-axis should display the revenue bin as a categorical but Charticulator converts to numerical automatically.

![screenshot 523](https://user-images.githubusercontent.com/43861167/51267891-9bf57900-1973-11e9-8ee3-219133bc070e.png)

**Comment by digital-mining1** [comment]
@snapper911T, a simple solution for this is to use entries like A011, A021, A031 if you want categorical axis. And 11, 21, 31, etc. if you want numerical exis. 
I think that this issue can be closed with some help documentation.

**Comment by snapper911T** [comment]
Understood, but I still think the ability to change between generic types in the tool is beneficial. If I am building a visual I don't want to have to modify my data set to display something else just to adjust the typing. Charticulator responds differently depending on these types and the ability to adjust them allows for true flexibility in a somewhat creative tool.

**Comment by snapper911T** [comment]
working in latest release
