### ISSUE TITLE
Weird scaling bug for object size vs text size

### ISSUE THREAD

**Issue by snapper911T** [microsoft/charticulator#138]
In the below examples I have a circle glyph with field "sum of records lost" to adjust the size. I also have a text object which uses field "sum of records lost" for size as well. When i try to change the circle domain and range the text adjusts MUCH more than the circle. I would expect the text remains the size that was set and only the circle adjusts. I did notice that they share the same scale based on the aggregation..not sure if this is desired.

![screenshot 7](https://user-images.githubusercontent.com/43861167/51894004-739a5100-235b-11e9-84e6-9a5281e76cf6.png)

![screenshot 8](https://user-images.githubusercontent.com/43861167/51894025-801ea980-235b-11e9-9232-fdf96526ed88.png)

**Comment by bongshin** [comment]
@snapperlux you can avoid this issue by creating a new scale: hold down the SHIFT key while dragging and dropping a column name to the target field.

We will explain this in the tutorial. In addition, we will think about which (reuse a scale vs. create a new scale) is a better default.
