### ISSUE TITLE
Creating an Area Chart

### ISSUE THREAD

**Issue by snapperlux** [Microsoft/charticulator#147]
Trying to create an area chart by linking (band) rectangles and then reducing the rectangle so its gone. Unfortunately, I can get it close but there are still very small lines for each square. and when I change the width to 0 (as in the second pic) the area links go weird. Is there a better way to create and area chart?

![screenshot 10](https://user-images.githubusercontent.com/43861167/52327859-67894180-29a2-11e9-80c1-5e777a17e211.png)

![screenshot 11](https://user-images.githubusercontent.com/43861167/52327863-6b1cc880-29a2-11e9-93a0-ebb66d8ed817.png)
[area.zip](https://github.com/Microsoft/charticulator/files/2835328/area.zip)

**Comment by snapper911T** [comment]
This doesnt seem to have fixed the issue as I am still seeing lines between bands. Is there a trick to minimize? Is there a better way to build an area chart?
