### ISSUE TITLE
Guides are not holding objects

### ISSUE THREAD

**Issue by snapper911T** [microsoft/charticulator#152]
added a horizontal guide as well as a vertical guide to place legends in below chart
![screenshot 19](https://user-images.githubusercontent.com/43861167/52679142-f1786380-2ee8-11e9-900b-4242b94fb7e1.png)

In Power BI the legends drop to the center of the chart.

![screenshot 20](https://user-images.githubusercontent.com/43861167/52679180-0fde5f00-2ee9-11e9-9723-3916aa6a7581.png)

**Comment by snapperlux** [comment]
This is still an issue in both the glyph area and the canvas. I have to use the square trick to get guides to persist when exported to PBIVIZ. See the attached example.
[traffic vs drugs v2.zip](https://github.com/Microsoft/charticulator/files/2981649/traffic.vs.drugs.v2.zip)
