### ISSUE TITLE
Enable the ability to scroll within a chart object: PBI

### ISSUE THREAD

**Issue by snapper911T** [microsoft/charticulator#167]
Allow the ability to scroll down within a chart. Similar to the default visuals. For example if you have a horizontal bar chart that has a large number of dimensions PBI will not try to cram the entire y -axis into the chart view box. It enables a horizontal scroll bar so you can scroll down and see the rest of the chart. Would be nice to enable or disable this feature based on requirements.

**Comment by NLondonLem** [comment]
This would be very useful for my work as well for Power BI custom visual exports

**Comment by vicinik** [comment]
This feature would indeed be very useful for large datasets.

**Comment by JSRossie** [comment]
Not as fancy as some use cases, but I'm making a data card visual and scrolling would be exceptionally useful.

**Comment by bongshin** [comment]
This issue is addressed in the recent release (Version 1.1.1).
