### ISSUE TITLE
Loading new data breaks positioning

### ISSUE THREAD

**Issue by ScriptPup** [microsoft/charticulator#171]
When I try to import a new csv all of my work is broken, every object in my glyph is centered together.

Glyph before new data:
![image](https://user-images.githubusercontent.com/6163646/60906950-fb0abb00-a23d-11e9-85c2-0febe738b55d.png)

Glyph after new data:
![image](https://user-images.githubusercontent.com/6163646/60906968-08c04080-a23e-11e9-8197-7b8e7f7146b4.png)

The site was really awesome up until that discovery :) I just need to add a few more columns so I can make more data fields to export as a PowerBI custom visual....

**Comment by snapper911T** [comment]
I have had his issue as well. I think it was due to the field names being off in my new csv or a different data type. Once I corrected things fell back inline.

**Comment by ScriptPup** [comment]
> I have had his issue as well. I think it was due to the field names being off in my new csv or a different data type. Once I corrected things fell back inline.

Were you able to add new columns at all? Or did the columns have to be 100% exactly the same for you?

**Comment by ScriptPup** [comment]
I checked what @snapper911T commented, trying to re-import the original (unmodified) csv file. It causes this same issue unfortunately.

**Comment by snapper911T** [comment]
I think the new columns came through ok. The field names have to be named exactly the same as the original file. You can usually find the culprit by slowly removing fields from the data driven objects and see how the viz responds

**Comment by ScriptPup** [comment]
Unfortunately I had the same behavior using the original file as well... So I'm not sure where to go from there :(

**Comment by snapper911T** [comment]
Make sure you lock objects to guides as that can cause issues. Unfortunately, a lot of times you have to try to reverse engineer things with charticulator to figure out what’s causing the issue. It does help with understanding. Hopefully MSFT puts a little more development into this in the future.

**Comment by ScriptPup** [comment]
Yeah, I ended up just redoing it. I think it may have to do with not having axises... I tried locking to guides as well, but no cigar on that working as a fix...

**Comment by snapper911T** [comment]
Yeah, if I had to redo a lot...usually easier. Plus you get better at understanding how it works. Still way faster than building this via D3 :)

**Comment by ScriptPup** [comment]
Very true! Thanks for the assist snapper!

**Comment by digital-mining1** [comment]
I used to face similar issue in the past. But eventually solved it. The trick is that every object needs to be anchored to something e.g. an Axis or another object. Once you do this, everything works fine.
