### ISSUE TITLE
Need ability to lock part of axis range (min or max)

### ISSUE THREAD

**Issue by snapper911T** [microsoft/charticulator#172]
Currently we can lock the range to a hard coded max and min amount or allow it to auto range. This causes an issue with bar charts as it will auto range to show just the relevant min and max and drop the 0 axis. We need the ability to lock the axis at zero and have the maximum scale auto range depending on data

**Comment by snapper911T** [comment]
This deems to be more a problem for PowerBI visuals. My workaround is to create a DAX measure: Measure=0 and just add to any charticulator data axis i want to lock at 0 in addition to my other measures.

**Comment by snapper911T** [comment]
@zBritva can you explain how this works?

**Comment by zBritva** [comment]
It's the same as

**Comment by zBritva** [comment]
Details:

We have a chart:
![image](https://user-images.githubusercontent.com/10897951/84242125-0f6bcd80-ab09-11ea-9292-271e48d1003a.png)
on creating I used values from 5 to 10

And in Power BI I have data values from 1 to 15, by default Charticulator updates min and max values for axis. In version before 1.6.0 you able only enable or disable it for whole axis.

In the new version, you can disable for max or min. When Charticulator will update only one side of axis:

![image](https://user-images.githubusercontent.com/10897951/84242400-7a1d0900-ab09-11ea-9b1f-09f46cd0ed71.png)

**Comment by snapper911T** [comment]
This has fixed the issue. To lock a data axis to 0 clear the MIN range (or set to 0) on your axis settings (pic1) and just untick the MIN autoscale when exporting (pic2)
![image](https://user-images.githubusercontent.com/43861167/88095936-bef58000-cb4a-11ea-80e4-3a16e7c8ca05.png)

![image](https://user-images.githubusercontent.com/43861167/88095843-98374980-cb4a-11ea-867e-b93306cde984.png)
