### ISSUE TITLE
How to create a stacked bar chart with a numerical y-axis ?

### ISSUE THREAD

**Issue by Justin-ZS** [microsoft/charticulator#174]
I can create a simple stacked bar chart like below.

![Screen Shot 2019-09-17 at 5 45 58 PM](https://user-images.githubusercontent.com/29063445/65030980-0b908d80-d973-11e9-9358-29d702a501ae.png)

I stuck immediately when I try to append a y-axis to it.
Dragging the `Value` dimension to y-axis just break everything and result in a strange chart.

![Screen Shot 2019-09-17 at 5 54 01 PM](https://user-images.githubusercontent.com/29063445/65031783-78f0ee00-d974-11e9-900b-abb9f227d373.png)

I found this [demo](https://charticulator.com/gallery/stock_msft.html) is very similar but the video doesn't reveal how to add a y-axis

How could I make it work?

**Comment by snapper911T** [comment]
Hey Justin, 
You need to add a "Data Axis to your Glyph panel. Watch this tutorial: https://charticulator.com/tutorials/tutorial9.html

Specifically the 3rd section. The example is a horizontal bar chart but it doesn't really matter as you would just apply your data axis vertically to the guides instead of horizontally.

Hope it helps!

**Comment by Justin-ZS** [comment]
@snapper911T 
Thanks, It does help me to add a y-axis.
However, it is bonded to every rectangle rather than stacked one.

![Screen Shot 2019-09-18 at 3 53 40 PM](https://user-images.githubusercontent.com/29063445/65128725-89649f80-da2c-11e9-8270-fa498ac6f1fc.png)

The y-axis should indicate the sum of stacked value dimension(group by another dimension) rather than individual value.

I only use the built-in dataset to paint, can you give me more tips?

**Comment by MikeCarlo** [comment]
Can you share the Charticulator.charts file so I can test it?

mike

**Comment by snapper911T** [comment]
I misunderstood originally what you were trying to do. With a stacked chart you need to create it as you did originally then just draw a "Data axis" to label your Y-axis. It wont be connected to anything but it will scale accordingly because they share the same data field.

Try this example (attached)

[stacked example.zip](https://github.com/microsoft/charticulator/files/3629395/stacked.example.zip)

**Comment by Justin-ZS** [comment]
@snapper911T 
Hi, I have tried the attached example chart and found some problems.
1. All bars in the same year are overlapped rather than stacked. 
1. The y-axis is scaled accordingly indeed but data bars wouldn't scale automatically when I change the range of the y-axis.

**Comment by Justin-ZS** [comment]
@MikeCarlo 
This is my stacked bar chart without a y-axis.
[demo (1).chart.zip](https://github.com/microsoft/charticulator/files/3630057/demo.1.chart.zip)

**Comment by MikeCarlo** [comment]
I was able to figure it out.  See if this works for you.

Steps:
1. **Add** a second Glyph, 
2. **Click** on new Glyph, add a 2D Region plot segment
3. **Add** months to the x-axis
4. **Click** on the new plot segment, click on Group By at the top of the Attributes window, Select **Month**
5. Add **Value** to the y-axis
6. **Click** on the Link button next to **Y Axis: Numerical**
7. When the window opens up **Change** the **Value** from average to **SUM**
8. **Adjust** the Range of the Y Axis to start at 0.
9. **Re-Arrange** the two charts to align against the guides on the page
10. **Click** the X-Axis Categorical to not be visible.

see attached image and Chart file for reference. 


<img width="943" alt="1" src="https://user-images.githubusercontent.com/25160592/65262605-57a51480-dad0-11e9-92ee-14983651554e.png">

[demo.zip](https://github.com/microsoft/charticulator/files/3632283/demo.zip)

**Comment by Justin-ZS** [comment]
@MikeCarlo 
Thank you!
I could understand all the steps and reproduce it by myself.
I also found that if I change the **range** of Y-axis from `[0, 180]` to `[0, 200]`, the bar height would not **change** automatically and accordingly.
Is there any way can link them together?

**Comment by bongshin** [comment]
You can show the y-axis (with tick marks) by adding a legend for the height scale: click on the "Add Legend" button from the scales panel (for the rectangle height). 

**Before you add a legend:**
![image](https://user-images.githubusercontent.com/9288805/65462612-03b96900-de0b-11e9-9343-9b491833b0ec.png)

**After you add a legend (and change the range):**
![image](https://user-images.githubusercontent.com/9288805/65462639-12a01b80-de0b-11e9-8735-f1451b4940ab.png)

**Comment by snapper911T** [comment]
...wow.....I did not know that! Thanks @bongshin

**Comment by Justin-ZS** [comment]
@bongshin 

Thank you! a clean and clever approach.

By the way, I want to ask a related question
How to understanding the second picture attached at first and produced by dragging the `value` dimension to `y-axis`?
Each bar's position is messed and some sub-layout options are disappeared too.

**Comment by bongshin** [comment]
Assigning the `Value` data column to the `y-axis` creates _a numerical axis_, which **positions** the glyphs based on their data values. So, in the second picture above, both the height and the y-position of the bars are determined by the `Value` data.

Note that Charticulator uses sub-layouts for categorical axes to determine a within-group layout.
