### ISSUE TITLE
Visuals not displaying in Internet explorer 11

### ISSUE THREAD

**Issue by snapper911T** [microsoft/charticulator#176]
Powerbi visuals do not show up when viewing report In IE11. Seems like ever (modern) browser worked until my client mentioned IE. Any hope in getting a quick update to remedy this?

**Comment by digital-mining1** [comment]
Charticulator works with Chrome, Edge and Firefox as stated on its website. IE is no longer in active development by Microsoft, while Edge is. Also IE will not have the latest features for a modern browser. I think that this issue can be closed after capturing a similar comment in the Help documentation.

**Comment by zBritva** [comment]
Charticulator uses WebAssembly, [it isn't supported by IE11](https://caniuse.com/#feat=wasm)

**Comment by snapper911T** [comment]
dumb request, anyways :)
