### ISSUE TITLE
Can I create a stack chart where each stack will contain its own values?

### ISSUE THREAD

**Issue by perezgt** [microsoft/charticulator#177]
I am new to Charticulator and I been using Charticulator to try to create a Stack Chart that will include the total for each group, and a total value per month. In Power BI I can create a stack chart but I can not apply a total to my chart. (Well I did but it is not clean I had to do 2 graphs and have one in front and one in the back). 
Tried to follow the following example but it is not working for me. At first I thought I was not anchoring my stacks but I have tried everything.  https://charticulator.com/gallery/food_supply_per_capita.html but it does not work for my chart.
[
![image](https://user-images.githubusercontent.com/56461632/66783838-a2c30500-ee8d-11e9-8137-44b4f6cdf202.png)
](url)
My data is as follows:
Month_Year, GroupA, GroupB, GroupC, GroupD, and GroupE. Note: Group E is my total. Tried to also follow the example given by https://github.com/microsoft/charticulator/issues/174 but the situation is different. 

Your feedback is greatly appreciated. 

TP

**Comment by perezgt** [comment]
Also, is there a way to put commas in the values as shown above. In Power BI I can do this but not sure what to add in the text command "${avg(GroupA)}{.0f} "

**Comment by bongshin** [comment]
@MikeCarlo has created a great tutorial that answers your first question. Please check it out at https://powerbi.tips/2019/11/stacked-bar-chart.

Charticulator's format specifier follows [d3’s syntax](https://github.com/d3/d3-format#format): The comma (,) option enables the use of a group separator, such as a comma for thousands. Try to set the text field to "**${avg(GroupA)}{,}**".

**Comment by MikeCarlo** [comment]
Here is my full list of videos on creating Custom Visuals: https://www.youtube.com/watch?v=KmZRjGQ9pdQ&list=PLn1m_aBmgsbERyYFzhwpHb1O3n--Al-jr

Mike
PowerBI.Tips
https://PowerBI.Tips
