### ISSUE TITLE
Conditional visibility is global instead of glyph/element local

### ISSUE THREAD

**Issue by peterbud** [microsoft/charticulator#186]
I have a chart with multiple plotsegments and each plotsegment contains a glyph with a label (text element).

**Current behavior:** 
I have defined a **conditional visibility** for one label/text using a field called "ChangeDirection" like `first(ChangeDirection)` and selected a subset of values (ChangeDirection is a categorical field with a few potential values), for which I wanted to see this label. It was working fine, label/text only appeared according to the filter selection.

When I have tried to do a similar to another text element in another glyph in another plotsegment, it turned out that if I select a different subset of values at the conditional visibility for `first(ChangeDirection)`  that also applies to the previous glyph - basically it seems that conditional visibility is global, and I cannot specify separately for the chart elements.

I have tried to "trick" the system, I was able to specify a different setting using a conditional filter on `last(ChangeDirection)` , but that was also global, I was not able to define more conditional visibility for the chart, without overwriting the previous.

**Expected behavior:** conditional visibility setting can be configured separately for each element.

**Comment by snapper911T** [comment]
So there is a trick to this. Charticulator defaults to existing scales and filters unless you specify. When you drag the field for Plot 2's visibility make sure you hold down shift. This will create a new scale/element and not re-use.
Learned this in: https://github.com/microsoft/charticulator/issues/138
Hope it helps!

**Comment by peterbud** [comment]
Thanks @snapper911T , it does work indeed! Great trick!
