### ISSUE TITLE
Awesome tool! But I found two issues

### ISSUE THREAD

**Issue by fabioc-ms** [microsoft/charticulator#188]
I created a visual that I plan to use in Power BI. The result on the Web UI was great, exactly what I was looking for. This is a fantastic tool!

I imported the visual in Power BI Desktop but could not save the pbix file. When I try to save, it raises the error saying that the file path is invalid. This happened on an existing file and also in a new file that I created to try to replicate the issue. So, I currently cannot use my creation. 

The second issue is that in the creation process I added an removed elements from the visual as I tried different designs. In the export to Power BI dialog, I still see exposed properties for elements that were deleted. 

I wonder if both issues are correlated.

Thanks 

Fabio Correa (at Microsoft)

**Comment by MikeCarlo** [comment]
Not sure about Issue #2, but for issue #1, make sure you are saving your creation with no spaces in the file name.  Second make sure you are allowing visuals to be used that are not certified within the Power BI Desktop Program.  This can be found under the options.  File -> Options and Settings -> Options -> Security -> Certificate Revocation Check & Data Extensions should be turned off.  Those might be causing issues.

Mike
PowerBI.Tips
https://PowerBI.Tips

**Comment by snapper911T** [comment]
In regards to the second issue. I have found its a lot nicer (more efficient) if you play around until you design what you need; then create another visual that is exactly what you need for the final chart to display. You can go through Charticulator and cleanup areas but it just seems a little clunky.

**Comment by fabioc-ms** [comment]
It looks like the space in the file name or the visual name caused the first issue. Eliminating spaces did the trick.

**Comment by bongshin** [comment]
Both issues are addressed in the latest release (Version 1.6.0).

**Comment by bendejong** [comment]
In my company the Non Certified Visuals are not allowed, is there a possibility to use the Charticulator visuals anyway?

**Comment by zBritva** [comment]
@bendejong Exporting to Power BI creates Power BI Visual. Power BI applies the same rules for all visuals. If Non Certified Visuals are not allowed you can't use Charticulator's visuals.

Visuals created by Charticulator cannot be certified automatically. Each visual have to pass certification process:
https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-certified

**It means each time, when you export chart to Power BI, you have to submit the .pbiviz file to certification and wait approval before start to using in Power BI.**

Topic similar to your cquestion: https://github.com/microsoft/charticulator/issues/227
