### ISSUE TITLE
What is the syntax for filtering a PlotSegment?

### ISSUE THREAD

**Issue by MikeCarlo** [microsoft/charticulator#189]
I am trying to apply a filter to a PlotSegment... What is the syntax needed to filter the Plotsegment to a value from a data column.. .

My data column has numerical values [1,2,3,4...] within it.  
I want to filter the plotsegment to have a value of column value of 1 
so an expression like [ColumnName] = <NumberValue>

Here is what I have tried...
![Expression2](https://user-images.githubusercontent.com/25160592/70735328-e043e300-1cc2-11ea-9b69-d3a1ed126f08.png)

Can anyone help me out with the syntax for this:
![expression](https://user-images.githubusercontent.com/25160592/70735460-2d27b980-1cc3-11ea-8338-ff95c2bf951e.png)

**Comment by MikeCarlo** [comment]
Never-mind, I figured it out.. You can use the following expression **Impact == 1**  which follows the format of [Column Name] == <Value within Column>

**Comment by snapper911T** [comment]
hey Mike,
I just used a simple syntax as shown in the photo

![Screenshot (441)](https://user-images.githubusercontent.com/43861167/70755839-ca004c00-1cef-11ea-8c62-cbb3bc68b55f.png)
