### ISSUE TITLE
Ability to wrap text

### ISSUE THREAD

**Issue by brucethurtell1** [microsoft/charticulator#192]
Is there a way to wrap the text when positioned within a polar chart? 
<img width="249" alt="Charticulator Text Wrap Option" src="https://user-images.githubusercontent.com/60131574/72789020-c46d1e80-3c2a-11ea-9235-8784312a1f9f.PNG">

**Comment by bongshin** [comment]
This feature is deployed in the latest release (Version 2.0.0).
