### ISSUE TITLE
Links don't work when glyph has guide

### ISSUE THREAD

**Issue by zBritva** [microsoft/charticulator#200]
**Reproducing steps:**
1. Add guide to glyph
2. Create the link

**Problem:**
Click to "Create link" doesn't create the links in the chart

**Expectation:**
Click to "Create link"creates the links in the chart, even if glyph has guide.

**Additional info:**
Exception on console:
![image](https://user-images.githubusercontent.com/10897951/76607779-99fe5a00-6525-11ea-8300-764d3fed8a08.png)

Source: https://github.com/microsoft/charticulator/blob/50f5c1a65ed4a71bbd318000eba80b1a4d27b182/src/app/views/panels/link_creator.tsx#L207

**Images:**
![charticulator_links_glyph_guide](https://user-images.githubusercontent.com/10897951/76607626-54da2800-6525-11ea-8e11-130c5439a7bf.gif)

**Comment by danmarshall** [comment]
From the GIF it appears that the guide is depending on the mark. Since this is no longer enabled by #247, bug seems to have gone away
