### ISSUE TITLE
When adding data binding to link data color it breaks PBIVIZ

### ISSUE THREAD

**Issue by snapper911T** [microsoft/charticulator#206]
Works great until I add a field to the link color then will not render in PBI:

![Screenshot (655)](https://user-images.githubusercontent.com/43861167/77216031-c3465980-6ad4-11ea-8172-3a766a79af67.png)

**Comment by zBritva** [comment]
On export to Power BI, it exports only source_id and target_id columns. It's limitation of current implementation. @bongshin do I need to extend it to support all used columns of the links table?

**Comment by bongshin** [comment]
@zBritva it makes sense to export the used data columns from the links table.
