### ISSUE TITLE
Logarithmic scale not working

### ISSUE THREAD

**Issue by snapper911T** [microsoft/charticulator#211]
When converting my Y  axis to Logarithmic scale it just seems to remove the Y axis altogether.

![Screenshot (663)](https://user-images.githubusercontent.com/43861167/77605910-5e737080-6ed3-11ea-8671-f2532222c9a8.png)

After:
![Screenshot (664)](https://user-images.githubusercontent.com/43861167/77605928-69c69c00-6ed3-11ea-8226-c6a0e7d26712.png)

**Comment by snapper911T** [comment]
hmm actually this seems to work for other datasets. Anyone else have this issue?

**Comment by zBritva** [comment]
The range starts from 0.

**Comment by snapper911T** [comment]
oh geez....its late...closing issue.

🤦
