### ISSUE TITLE
Logarithmic axis do not seem to work

### ISSUE THREAD

**Issue by flaviotti** [microsoft/charticulator#221]
Hello,

I have a feeling that I must have missed something, but I have studied the instruction and getting started material carefully and I didn't find anything that mentioned this issue.
On a regular Cartesian plot segment, every time I chose logarithmic as a scale for any of the axis, the glyphs are placed back into the middle, and the axis don't seem to recognize how to place the data anymore.
My apologies if this is an error on my end. In that case please consider this as an enhancement for the documentation. 

I find charticulator a fantastic tool, and I am very grateful for the effort put to make it available to us.

Regards,
/Flavio

**Comment by zBritva** [comment]
Hello @flaviotti, could you check that issue is similar to https://github.com/microsoft/charticulator/issues/211?

**Comment by flaviotti** [comment]
@zBritva 
Hi LLfat,
yes, looks like is the same issue. It happens for either and both the X and Y axis. I did a search for logarithmic before opening the issue, but I didn't see that one. Apologies for the duplication.

**Comment by flaviotti** [comment]
Hi @zBritva ,
I finally understood how to make it work. Not only data axis shouldn't have any 0, but also we need to remove the 0 from the minimum value of the axis properties which nonetheless charticulator set to 0. 
My recommendation would be to specify this in the documentation, or to avoid that the minimum value is set to 0 when logarithmic is selected, especially when there is no 0 axis value in the data file used. 
But all in all, very minor stuff. I am glad I can work with logarithmic. 
Cheers,
/Flavio
