### ISSUE TITLE
Can´t load CSV file to Charticulator

### ISSUE THREAD

**Issue by wickstromhelena** [microsoft/charticulator#223]
Hi, I´m trying to load data from a CSV file to Charticulator, but it doesn´t recognize the columns, see below. Is semi colon not a valid delimiter in Charticulator? 
![image](https://user-images.githubusercontent.com/63495145/79318494-5a050b00-7f07-11ea-8f83-ef9ad9e00563.png)

Thanks,
Helena

**Comment by zBritva** [comment]
Hello @wickstromhelena, change the delimiter to comma as workaround

**Comment by wickstromhelena** [comment]
Hi @zBritva 
Thanks for your reply. I changed it to "," in the regional settings, see below. But that does not do the trick (I have restarted the computer and created a new test .csv file)
<img width="323" alt="Capture" src="https://user-images.githubusercontent.com/63495145/79331813-110b8180-7f1c-11ea-8e0d-1ea1d88107cd.PNG">

**Comment by zBritva** [comment]
@wickstromhelena And what do you get on loading to the charticulator? the same view?:
![image](https://user-images.githubusercontent.com/10897951/79332586-c55dd580-7f25-11ea-991b-a2092051ce12.png)

**Comment by wickstromhelena** [comment]
@zBritva  yes..

**Comment by zBritva** [comment]
Did you save the file with comma? If the preview of file exactly the same, it was saved with `;` instead `,`

**Comment by wickstromhelena** [comment]
@zBritva, I opened a new Excel sheet, typed some example data and saved as .csv file. How do you mean that I can save with comma?

**Comment by zBritva** [comment]
@wickstromhelena  do you see the similar?

![image](https://user-images.githubusercontent.com/10897951/79334722-7fa30c00-7f29-11ea-911f-c6d3f9324244.png)

Could you share no private sample here?

**Comment by wickstromhelena** [comment]
Yes, I´m choosing that. Please find attached a sample file, I can see that it still gets the ";" delimiter, despite having changed the regional settings and restarted the computer and created the sample file after changing the regional settings..


[CSV test2.zip](https://github.com/microsoft/charticulator/files/4481089/CSV.test2.zip)
