### ISSUE TITLE
Unable to open exported chart file in PowerBI

### ISSUE THREAD

**Issue by wickstromhelena** [microsoft/charticulator#224]
Hi
When I try to export a CHART file from Charticulator to PowerBI I get the below error message. There are no blank spaces in file or visual name. 
Please find attached the applicable files, would very much appreciate if someone could test and see if the chart file works to export for you, and if you have any idea why I have this problem.
Thanks,
Helena

<img width="345" alt="Capture" src="https://user-images.githubusercontent.com/63495145/79320460-25df1980-7f0a-11ea-8635-51a6b09d25b4.PNG">

[Clustered Stacked Column.zip](https://github.com/microsoft/charticulator/files/4480213/Clustered.Stacked.Column.zip)

**Comment by zBritva** [comment]
@wickstromhelena I checked the files. The visual works for me. 
Could you tell the version of Power BI Desktop? Did you try to import the visual in the Power BI Service?

![image](https://user-images.githubusercontent.com/10897951/79322280-452f7400-7f15-11ea-9068-bcd422e57984.png)

**Comment by wickstromhelena** [comment]
Hi @zBritva,
I saw that I used the wrong type of file format, so it is solved now. Sorry for taking your time!
/Helena
