### ISSUE TITLE
Nested chart to achieve stacked and clustered column chart? 

### ISSUE THREAD

**Issue by wickstromhelena** [microsoft/charticulator#225]
Hi,
I want to achieve a stacked and clustered column chart, and made an attempt but I need the data sets (forecast and actual) to have the same Y-axis. I suspect that I need to make a nested chart but do not manage to get the desired result, and have found no tutorials online for making a nested chart. Would very much appreciate support in creating one or recommendations on tutorials! 
Thanks,
Helena
[Charticulator data.zip](https://github.com/microsoft/charticulator/files/4481919/Charticulator.data.zip)

**Comment by dm-p** [comment]
Just saw this issue and wanted to add that I did a [basic sample for this on the original PBI Community forum post](https://community.powerbi.com/t5/Custom-Visuals-Development/Custom-visual-made-with-Charticulator-not-respecting-scale/m-p/1161207/highlight/true#M3241) in case anyone else is wondering how.

**Comment by bongshin** [comment]
I'm closing this issue because there is no further discussion.
