### ISSUE TITLE
Date values are not properly handled

### ISSUE THREAD

**Issue by bongshin** [microsoft/charticulator#231]
For example, date values are sorted incorrectly.

![image](https://user-images.githubusercontent.com/9288805/81248787-03549380-8fd2-11ea-8f47-07ec292ce53d.png)

**Comment by TP-analyst** [comment]
Hi bongshin,

I tried to upload date data to both the x and y axis in Charticular, but as you saw in your example, the date sequence is not correct.  I believe the platform treats dates as text, and so it sorts accordingly to alphanumeric order.  

Example data:
![image](https://user-images.githubusercontent.com/65028291/81415776-dfe73100-9116-11ea-96e7-e7cdabdb545b.png)

What I am hoping to get (created in Matlab, ignore red line): 
![image](https://user-images.githubusercontent.com/65028291/81416630-fb9f0700-9117-11ea-8ff2-552b63e5532c.png)


What I actually get:
![image](https://user-images.githubusercontent.com/65028291/81416448-c09cd380-9117-11ea-8b66-6495b4cba6b5.png)

**Comment by zBritva** [comment]
Expects formats of Charticulator:
 - DateFormats:
   - YYYY-MM, YYYY-MM-DD
   - MM/YYYY, MM/DD/YYYY
 - TimeFormats:
   - HH:MM, HH:MM:SS
   - HH:MM{am/pm}, HH:MM:SS{am/pm}
 - TimezoneFormat:
   - +HH:MM, -HH:MM

**Comment by TP-analyst** [comment]
OK, I think I understand the issue - DateFormat:  MM/DD/YYYY requires 1/1/2019 dates to appear as 01/01/2019.  Is there any way to automatically detect and reformat date data on Charticular?

Theresa

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.6.0).
