### ISSUE TITLE
Drillthrough

### ISSUE THREAD

**Issue by DarwishNakouzi** [microsoft/charticulator#233]
Is there a way to enable  drill through functionality for Charticulator Charts in power bi?

**Comment by zBritva** [comment]
Duplicate of https://github.com/microsoft/charticulator/issues/141

**Comment by snapper911T** [comment]
this is working currently

**Comment by DarwishNakouzi** [comment]
I tried to right click checked the format but I could not find anything regarding drillthrough! If its working can you show me how?

**Comment by zBritva** [comment]
I suspect you checked it in https://charticulator.com/
The latest changes aren't deployed yet. And I don't know when new version will be deployed.

**Comment by bongshin** [comment]
The latest version (1.6.0) of Charticulator was deployed yesterday (June 15, 2020).

**Comment by DarwishNakouzi** [comment]
thanks for the update, I have enabled drilldown and I exported it. However, when I right click it is still not appearing! can you show me how it works?

**Comment by snapper911T** [comment]
Keep in mind "drill down" is not supported. Drill through is though. You need to setup a secondary tab with the field you want to drill through.

**Comment by DarwishNakouzi** [comment]
I did already but It only worked on a Dimension and not a measure.
