### ISSUE TITLE
Dataset Panel disappears after loading new data

### ISSUE THREAD

**Issue by bongshin** [microsoft/charticulator#242]
After loading new data with less items, causing the change in an axis (e.g., no more 'MINI' and 'Porsche'), the dataset panel disappears.

**Before**
![image](https://user-images.githubusercontent.com/9288805/82127594-ad1de800-9769-11ea-9f1d-5c376a893150.png)

**After**
![image](https://user-images.githubusercontent.com/9288805/82127590-a2fbe980-9769-11ea-9649-4a338c9a1d8d.png)

**Comment by snapper911T** [comment]
This looks like its working now
