### ISSUE TITLE
Will the version number of Charticulator be updated with the latest changes?

### ISSUE THREAD

**Issue by nadiafank** [microsoft/charticulator#244]
Hi @zBritva 
thank you so much for your amazing work! 

I have a consultation to check my local version of Charticulator. Will the version number be updated with these changes or will version 1.4.0 be maintained?

Thanks!!

**Comment by zBritva** [comment]
master branch has 1.6.0 version number. This version wasn't deployed yet

**Comment by nadiafank** [comment]
You have an idea of when that will be, thank you very much.

**Comment by bongshin** [comment]
The version 1.6.0 of Charticulator is deployed today (June 15, 2020).

**Comment by nadiafank** [comment]
Great news. Thank you!
