### ISSUE TITLE
powerbi may 2020 update broke lots of things

### ISSUE THREAD

**Issue by trivita** [microsoft/charticulator#249]
categorical axis sort doesnt behave normal

visibility condition doesnt work as it should

**Comment by snapper911T** [comment]
Yes, we are waiting for the updates to be approved and merged into MASTER. 
Please help in capturing the items you are seeing in separate issues with reproducing steps and pics.

**Comment by trivita** [comment]
![Snipaste_2020-05-31_12-09-45](https://user-images.githubusercontent.com/1425147/83344374-68cd4300-a338-11ea-82fe-7dab593c533a.png)

in this picture (PBI 2020 may release)
1. X axis is categorical, but the sort is wrong
1. tooltip doesnt follow cursor, it stays on the upper-left corner
1. visibility control works in charticulator app, but not in PBI
