### ISSUE TITLE
Visuals does not support Exporting in Power bi Service 

### ISSUE THREAD

**Issue by DarwishNakouzi** [microsoft/charticulator#256]
when you I export a report in power bi service to a pdf a file, Its giving me this error "This Visual does not support exporting"

**Comment by zBritva** [comment]
Export to PDF, PowerPoint file or share by e-mail requires certification:
https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-certified

Only certified visuals can be rendered on export.

**Comment by Minova2018** [comment]
Do you expect Charticulator will receive this certification in the future?
