### ISSUE TITLE
Charticulator charts are not working with cube

### ISSUE THREAD

**Issue by DarwishNakouzi** [microsoft/charticulator#257]
Recently, I have downloaded  one of my saved chart in order to capture the latest updates. However, it did not work after I replaced my old visual with the new one in power bi! It kept on giving me "incomplete data" although all the required field are there. So I decided to create  a new power bi report and connect it with csv and all of a sudden it worked. Then I  tried with sql server database(directqeury mode) and it also worked fine. So why its not working with sql server analysis services?

**Comment by DarwishNakouzi** [comment]
I also would like to ask if there is a way have the old Charticulator version before the update as I can not move on with my project! Please let me know its urgent !

**Comment by zBritva** [comment]
@DarwishNakouzi 
Could you share the screenshot of fields bucket of the visual?

And could you ensure that all columns has "Don't summarize" option?

![image](https://user-images.githubusercontent.com/10897951/85166435-f503c380-b26f-11ea-9308-7d25607182be.png)

If you can share your visual, it will help to figure out the problem.

Thanks!

**Comment by DarwishNakouzi** [comment]
@zBritva  Thanks for your help. I was about to send you a screenshot of the visual. However, the visuals are working again! I have no idea what might have caused that but for now everything seems fine. Thanks again for your help
