### ISSUE TITLE
Don't summarize (no aggregation) in scatter

### ISSUE THREAD

**Issue by alexandervanroij** [microsoft/charticulator#259]
When using the standard scatter visual in Power BI desktop, you can choose "Don't summarize" to view all datapoints in the chart.
When creating a custom chatter visual in Charticulator and importing it in PBI desktop, you have to choose one of the aggregation options. 

is it possible to create a scatter chart in Charticulator that has the "Don't summarize" option?

**Comment by zBritva** [comment]
The latest version supports it.

**Comment by alexandervanroij** [comment]
thanks @zBritva, I was using an old version, sorry about that
