### ISSUE TITLE
Export to PowerBI Custom Visual in local server

### ISSUE THREAD

**Issue by doubleamp** [microsoft/charticulator#275]
Hello, and thanks for this amazing tool.

I am trying to create a custom PowerBI visual using charticulator. I need to show some numerical quantities and for those I have to use non-US formats ("." as thousand separator and "," as decimal separator, mainly). I tried to investigate how to do that using Charticulator options in charticulator.com but I was unable to do it. Therefore I have set up a local charticulator server, changed D3.js default locale and now the chart in my charticulator server displays the quantities the way I need. However, I am not able to export the chart to a custom visual; the option is not shown in the Export menu (see image below). Do I need to do something else to build this functionality into the local server?

Info: my local server runs on HTTP, not HTTPS. I do not know if that may make any difference for the PowerBI export.

![Clipboard-20200711](https://user-images.githubusercontent.com/7216442/87227141-25cfa800-c399-11ea-9108-4be02fbd4924.png)

**Comment by zBritva** [comment]
@doubleamp Hello! You need to install the extension: https://github.com/microsoft/charticulator-extensions/tree/master/powerbi-visual-builder

**Comment by doubleamp** [comment]
Perfect! Thank you so much again!
