### ISSUE TITLE
Dashed / dotted lines in 1.6.0

### ISSUE THREAD

**Issue by doubleamp** [microsoft/charticulator#276]
I have seen a previous issue regarding dashed / dotted lines (issue #173), now regarded as closed saying that 'it is now a feature'. However, I can not see how to use this option in the current 1.6.0 version. The attributes for line objects do not show this capability... how can I use the new functionality?

Thanks in advance.

![Clipboard-20200711-01](https://user-images.githubusercontent.com/7216442/87227378-d0949600-c39a-11ea-89d9-972d749e3464.png)

**Comment by zBritva** [comment]
The feature made for links lines, not for a line object.

**Comment by doubleamp** [comment]
Ah, OK, I misunderstood the capability then. Any chance that this functionality is added to the line object?

Thanks again.

**Comment by zBritva** [comment]
@bongshin what do you think?

**Comment by doubleamp** [comment]
Thank you very much to all. It works perfectly!
