### ISSUE TITLE
Turn tool tips on or off for each plot segment or object

### ISSUE THREAD

**Issue by snapper911T** [microsoft/charticulator#281]
sometimes when I create a plot segment to add a square or grid lines or other formatting objects a nasty large tooltip will appear when mousing over.
In the example below I am mousing over a square glyph on a plot segment in the background which is used as formatting:
![Screenshot (930)](https://user-images.githubusercontent.com/43861167/87608698-6f7c0380-c6b5-11ea-820a-bbca2554018b.png)

**Comment by snapper911T** [comment]
Another simpler example:
In the below pic I have 2 plots. The first one is the basic bar chart (orange bars). The second plot is just horizontal bars with no data bound to them...but they still show a tooltip.
 It would be great if we could control the tooltip on/off for each plot in a visual.
[datatest.zip](https://github.com/microsoft/charticulator/files/4962510/datatest.zip)




![Screenshot (947)](https://user-images.githubusercontent.com/43861167/88226985-c3409c80-cc21-11ea-9ebb-eebc2cfe7595.png)

**Comment by snapper911T** [comment]
Another example of how this is frustrating!

![Untitled - Power BI Desktop 7_23_2020 5_08_31 PM](https://user-images.githubusercontent.com/43861167/88350195-396aff00-cd07-11ea-9e5e-6983fccff9cd.png)

**Comment by bongshin** [comment]
This issue is addressed.
