### ISSUE TITLE
Need ability to wrap text objects

### ISSUE THREAD

**Issue by snapper911T** [microsoft/charticulator#283]
Would be a helpful feature to allow data labels and axis labels to "wrap" if too big for an object or area.
Any text labels can become a mess if there is not a smart way to handle them...usually it seems to be a combination of wrapping and auto display or some other tricks.

Wrapping would be a good first start.

**Comment by doubleamp** [comment]
An alternative might be to allow Charticulator to interpret / display line breaks in text strings. I have tried to insert '\n' and '<br>' substrings in string data but it simply displays these character, it does not act on them. Or is there any other way to insert these line breaks?

**Comment by snapper911T** [comment]
yeah! Some ability to have the line break be driven by a data field would be cool. Could base it on the number of characters using DAX or something...

**Comment by doubleamp** [comment]
I very much look forward to this functionality being implemented. I have tried to understand the code to see where it could be changed to support it. I believe that the use of the current Textbox mark (that cuts overflowing text in the boundaries) is the place to change it, but I may be wrong and some new mark is the way to go.
Provided that current Textbox could be changed, I suspect that making it not subject to constraints could help, but I honestly do not know yet the impact of the constraints. On the other hand, a wrapping function has to be implemented (I have found some examples looking around in the Internet), but I am not sure yet if this has to be put into the .ts file for the mark, or on the global renderer, or somewhere else, or I am completely wrong.
I am willing to research more and try to implement a solution for this, but if @danmarshall , @zBritva or someone else could point me in the right direction I would probably mess much less.

**Comment by zBritva** [comment]
@doubleamp 

The start point is:
https://github.com/microsoft/charticulator/blob/master/src/core/prototypes/marks/textbox.ts#L215

The method responsible for graphics of text (how it will be rendered)

But it is TextBox, not a Text object:

![image](https://user-images.githubusercontent.com/10897951/89033031-92a5e480-d33e-11ea-8f98-3aab1559464c.png)

Text object represent a point in "engine" of Charticulator, and you will not able to figure out, is there enough space for text or not.

[`attrs`](https://github.com/microsoft/charticulator/blob/master/src/core/prototypes/marks/textbox.ts#L221) object contains size of text box, it could help to compare the size of box and size of text from [`metrics`](https://github.com/microsoft/charticulator/blob/master/src/core/prototypes/marks/textbox.ts#L231) object, so you can figure out do you need wrap text or text fits current box.

Pay attention, box has height to, so, you can't draw the text outside of box.

You can add property to control the feature (enable/disable wrapping) here:
https://github.com/microsoft/charticulator/blob/master/src/core/prototypes/marks/textbox.ts#L44

and define UI element for editing this property:
https://github.com/microsoft/charticulator/blob/master/src/core/prototypes/marks/textbox.ts#L90

the method responsible for view of attributes panel:
![image](https://user-images.githubusercontent.com/10897951/89033741-29bf6c00-d340-11ea-8294-cfeb61509957.png)

**Comment by zBritva** [comment]
I can't promise you that feature will be implemented. Ask details from @bongshin

**Comment by snapper911T** [comment]
Please @bongshin ??? :)

**Comment by doubleamp** [comment]
I have tried my hand with this functionality, as pointed by @zBritva . I am able to split the text into several chunks, depending on the size of the TextBox and the length of the text. But I am not being able to show these chunks as separate entities. I would say that the 'getGraphics' method just displays one of the chunks (I suppose that when the 'return' is invoked for the textElement object), so my attempt to display each of the chunks with different 'helper' object does not work. Then I have turned to use a single 'helper' with a text string that concatenates the different chunks with intermediate line feed characters, but this do not seem to work either: '\n', '\r' or '\r\n' have no effect in the displayed text, '<br>' or '<br/>' show as literals between the chunks, and so I end mostly with the same original text in a single line, that is longer than the available width. Can anybody provide further tips to go on from this point?

**Comment by doubleamp** [comment]
In the previous comment, the strings '< br >' and '< br/ >' (remove the spaces) are shown as line breaks in my text after the '...have no effect in the displayed text, ...', sorry for it. But these strings do not have this effect in Charticulator :-(

**Comment by bongshin** [comment]
This feature is deployed in the latest release (Version 2.0.0).
