### ISSUE TITLE
Option for gaps in link across missing data points

### ISSUE THREAD

**Issue by Invigor** [microsoft/charticulator#288]
Hi,

We are interested in using Charticulator to create a custom line chart visualisation which does not display any line between missing data points.

The specific use case is for time-series product pricing and how to handle the days when a product is unavailable.

Our data is daily price and if a product is not available for several days we would like the line to discontinue until the product is available again.

The current behaviour for links is to "link" all sequential data points so we end up with a diagonal line spanning the missing data as show below.

![image](https://user-images.githubusercontent.com/15044031/87908407-ac773a00-caa9-11ea-9267-2f90f9e2fa77.png)

I'm hoping there is already a way to do what we need otherwise it would be great to have this functionality added to the tool.

Thanks,

Michael

**Comment by snapper911T** [comment]
You should have a gap in your line if you setup a continuous date dimension and use the date field from the dimension table.
or
Just make sure your data set has a date for the missing values like the screenshot below :)
![image](https://user-images.githubusercontent.com/43861167/87988134-af1b6480-ca94-11ea-8450-8a7e73bea7ef.png)

**Comment by Invigor** [comment]
Hi @snapper911T ,

Thanks for the suggestion but having the line go to 0 suggests that the price is going to $0 which would be very confusing.

Cheers,

Michael

**Comment by snapper911T** [comment]
Right, sorry i responded too quickly! Only way I can see doing this as of now is creating a data/no data flag.
Wouldn't be too hard. but as typical with Charticulator if its not a feature yet... usually data manipulation will get it working :)

![image](https://user-images.githubusercontent.com/43861167/88000055-8b1a4c00-cab1-11ea-9c19-413c3d25a6b9.png)

**Comment by Invigor** [comment]
Found that the Multi Axes Chart from xViz does exactly what we need although it is a paid solution for Power BI Embedded.

https://xviz.com/visuals/multi-axes-chart/
