### ISSUE TITLE
Re-use a modified scale

### ISSUE THREAD

**Issue by snapper911T** [microsoft/charticulator#292]
In the image below my lines are based on the sport (scale 1). I have changed some of the lines colors to allow better  visibility. 
Now I want the text to use the same scale so i don't have to manually change each one again...how do i go about doing this? I cant drag and drop from scale pane. I have tried renaming text scale (scale 6) to scale 1 but it doesn't change anything.
See Boxing as an example:

![image](https://user-images.githubusercontent.com/43861167/88349875-2d327200-cd06-11ea-89a2-3f7959fb5ab6.png)

**Comment by bongshin** [comment]
The recent release (Version 2.0.0) addresses this issue. Also, how to reuse a scale is now documented on the Charticulator website.
