### ISSUE TITLE
Example (or template) needed for simple column chart

### ISSUE THREAD

**Issue by erapade** [microsoft/charticulator#298]
I have been trying to build a simple Clustered column chart. 
My first issue is that I can't even create a simple none clustered column chart. I Need to have a scale on both the x and y axis.
My second issue is that I can't get ride of the PrimaryKey requirement when importing the visual to Power BI. 
My third issue when trying to do a simple line chart is that the Power BI visual controls for sorting the x-axis data based on the values doesn't work. E.G. dropping YearMonth in the x-axis is unsorted, even if this column is sorted on YearMonthNumber, while dropping YearMonthNumber in the x-axis and it is sorted correctly, except that I can't change the sort order. This is probably since the visual overrides this

**Comment by erapade** [comment]
I managed to get around the first issue with values in the Y-axis by adding the legends from the Glyphs Rectangle binding properties, although I can't see this in any documentation. While this is one way, I can also imaging that creating a second Glyph and plot segment might also be a solution. But as I initially said, It would be good to add the y-axis in your examples

**Comment by doubleamp** [comment]
@erapade , maybe what is discussed in issue #174 is applicable to your use case as well...

**Comment by snapper911T** [comment]
if all you are looking to do is create a bar chart this video walkthrough should be enough:
https://charticulator.com/tutorials/tutorial9.html
You have to use the data axis to create your Y axis (as show in video). 

There are a few other videos which you can pick apart to understand some concepts.
https://charticulator.com/docs/video-tutorials.html
