### ISSUE TITLE
Accounts for development environment and/or sharing code

### ISSUE THREAD

**Issue by erapade** [microsoft/charticulator#301]
Hi, I'm trying to understand the bindings between my web-browser and the development environments as I can't see any login/logout. I'm trying to understand how to share my visual code with my colleges. One way could be to create a "service account" used by all my colleges, but a better solution would be to be able to share code with others.
I can see that I can save a template, but I can't see how I can import one

**Comment by zBritva** [comment]
Hello, 

You can download and import *.chart files (*.chart files contain data):

![image](https://user-images.githubusercontent.com/10897951/89171375-bf017100-d589-11ea-8bd9-520c24448a2e.png)

Template files are for nested charts only:

![image](https://user-images.githubusercontent.com/10897951/89171470-e5271100-d589-11ea-9678-9bc69f203e03.png)
