### ISSUE TITLE
BUG: Turning title off kills visual in PBI

### ISSUE THREAD

**Issue by snapper911T** [microsoft/charticulator#303]
Chart renders fine initially:
[KPI.zip](https://github.com/microsoft/charticulator/files/5023966/KPI.zip)

![image](https://user-images.githubusercontent.com/43861167/89332961-19add200-d649-11ea-93d5-db364de8f0e5.png)

Once I turn the "title" option off I cant get the chart to come back unless i delete the visual and rebuild it.
![image](https://user-images.githubusercontent.com/43861167/89332989-27fbee00-d649-11ea-80f0-c5544fcd4f22.png)

**Comment by snapper911T** [comment]
Also noticed when I click to another tab and click back the visual restores itself...

**Comment by zBritva** [comment]
@snapper911T Did you find it on deployed version or fetch the latest changes from repo?

I can't reproduce and I suspect it was fixed in https://github.com/microsoft/charticulator-extensions/pull/34

Thanks!

**Comment by snapper911T** [comment]
ok, I didn't realize I wasn't on the latest version :(
Just fetched the latest for both Charticulator and extension. I cannot reproduce.
