### ISSUE TITLE
BUG: Adding data to data axis doesn't persist after latest changes

### ISSUE THREAD

**Issue by snapper911T** [microsoft/charticulator#312]
Drag and drop a field on a data axis in the glyph window doesn't keep. 
See GIF below:

![example](https://user-images.githubusercontent.com/43861167/90661913-9a013500-e1fc-11ea-8ce5-4c4d54469f89.gif)

**Comment by zBritva** [comment]
Fixed:
![axis_data_expression_fix](https://user-images.githubusercontent.com/10897951/90671971-19732080-e25e-11ea-9aa6-5524894f7a5a.gif)

**Comment by snapper911T** [comment]
works again
