### ISSUE TITLE
In powerbi, the custom visual from charticulator, how to set the color in power bi?

### ISSUE THREAD

**Issue by luojiandan** [microsoft/charticulator#319]
the color can be setting in power bi?

**Comment by luojiandan** [comment]
and the color can be setting by category? the String field value.

**Comment by zBritva** [comment]
Setting of data bound colors is not supported at the moment. You can change only static colors for objects.

**Comment by luojiandan** [comment]
![01](https://user-images.githubusercontent.com/5663556/92504296-105de980-f235-11ea-8baa-b35e06504933.png)
thanks:),and is that in your plan?
