### ISSUE TITLE
Add features to Power BI visuals

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#324]
Hi, 
Would it be possible to add the following features to the custom visual for Power BI?
1. Copy + paste visuals
2. Enable , disable legends, titles,...
3. Add number format (k, auto, M, etc)
Thanks

**Comment by doubleamp** [comment]
I think all those features are already available:

1. I can copy & paste the Charticulator generated visuals between pages and between reports (in this second case you have to import the visual for it to work, as happens with any non standard visual)
2. If you want to use data to control elements visibility, you can use the 'Visibility' feature; if you want to control visibility 'on the fly' in PowerBI Desktop, you can do it in the Format section of the visual, for each individual element. Those related with text always have the 'Opacity' attribute that you can use for effectively showing / hiding them.
3. You can do that when specifying the format that you want the shown data to use; Charticulator follows D3 format, see 'Text Formatting' section at the bottom of https://charticulator.com/docs/user-interaction.html.
Regards,

**Comment by ruthpozuelo** [comment]
So sorry, I couldnt copy them yesterday, but if I wait a little now they do copy. Same for the rest. 
Some comments, 
It would be great to have the opacity as a toggle button like in the native visuals, same with the formatting of numbers.

Can I add two more requests?
1. Activate the Format Painter and
2. Is it possible to conditional format the Max value of a field in one color and the rest in another? Havent figured that out yet.

Thanks a million.

**Comment by doubleamp** [comment]
I do not know if the opacity / formatting can be managed with toggle buttons. It has to do with the charticulator exporter to PowerBI, which is a different element from Charticulator itself (see https://github.com/microsoft/charticulator-extensions). Probably you should post this comment / request over there (though I would say that the gurus there are the same than here). The same goes for your first additional request.
As for the second additional point, I do not think that it is feasible by itself in Charticulator (if it is, I do not know how to do it directly). What I would do is creating a separate field / column in your data that marks the max values (with a True/False, 1/0, whatever that may distinguish them), and then I would represent in Charticulator two sets of data, in the same place if you want in your glyph, and I would play with visibility of these data depending on the max-marker column. I have attached a chart example using the city temperature data. I hope it helps.

[City Temp-with Max.txt.chart.zip](https://github.com/microsoft/charticulator/files/5228617/City.Temp-with.Max.txt.chart.zip)

Regards,

**Comment by ruthpozuelo** [comment]
Perfect, thanks a million, that gave me an idea!!!
