### ISSUE TITLE
Opacity setting gone for marks in glyphs

### ISSUE THREAD

**Issue by doubleamp** [microsoft/charticulator#329]
Hello. I'd say that the 'Opacity' setting for fill color is no longer visible in the attributes panel for marks in glyphs. I have checked with the version currently published in charticulator.com and the option is there. Newer versions do not show it.

I have compared latest versions of the files with a copy that I had locally from 3-4 weeks ago, but I have not been able to find any relation to this bug...

Thanks,

**Comment by zBritva** [comment]
@doubleamp thanks! I included fix here: https://github.com/microsoft/charticulator/pull/328/commits/824c045454258e0ce7df93e7fa53826b3242187c

**Comment by doubleamp** [comment]
That definitely fixes it, @zBritva , thank you very much. Will you be committing this change in a future PR so that it flows to the current version? Thanks again. Closing this now.
