### ISSUE TITLE
Change color of shapes in PBI

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#331]
Hi,

Is it possible to change the color of the shapes in Power BI? I cant find that.

I see that I can change the legend or text elements, but not the shape. Maybe I just cant find it.

**Comment by zBritva** [comment]
If color of shape depends on data, you can't configure color in Power BI. Only static color properties can be changed in Power BI.

**Comment by ruthpozuelo** [comment]
I have managed to conditional format it (thanks to one of your colleagues) but I can't seem to find where to change the static color. Apologies if it is there, I cant see where.

**Comment by zBritva** [comment]
It doesn't supported:

![image](https://user-images.githubusercontent.com/10897951/93792733-91a67a80-fc3e-11ea-890d-8b918405f7c4.png)

If you bound data to color of shape, you can't change in Power BI.

It works, If simple color assigned:

![image](https://user-images.githubusercontent.com/10897951/93792834-b569c080-fc3e-11ea-8c16-d312a69a8605.png)

In visual properties find property with correspond name:

![image](https://user-images.githubusercontent.com/10897951/93792961-d9c59d00-fc3e-11ea-94f9-24c61ce007b4.png)

**Comment by ruthpozuelo** [comment]
Ok  now I understand why. Can that be changed?

**Comment by zBritva** [comment]
I didn't estimate it. I can't give answer.

**Comment by ruthpozuelo** [comment]
Ok, thanks
