### ISSUE TITLE
Date field in Charticulator and Power BI

### ISSUE THREAD

**Issue by leilaetaatiprogram** [microsoft/charticulator#334]
Hello, 
First thanks for this amazing no-code custom visual creator tool ( at least I am not a c# developer so I use the only designer. 
I start to create a Gantt chart in Charticulator, it works very well, But it does not show in Power BI when I imported.
 I am in NZ so I change all setting of Date to be USA date format from control pannel to Power BI to my data set, still not able to see it in Power BI, I attached both Charticulator and pbiviz 

[Downloads.zip](https://github.com/microsoft/charticulator/files/5345113/Downloads.zip)
Thanks
Leila

 file to this comment

**Comment by zBritva** [comment]
Hello, the fix for similar issue was in https://github.com/microsoft/charticulator-extensions/pull/38

Yesterday the latest version of the Charticulator was deployed. Could you export your chart to Power BI again and try to use.
I hope it will work. 

Thanks!

**Comment by leilaetaatiprogram** [comment]
Sure Will check it now

**Comment by leilaetaatiprogram** [comment]
I just checked it and it does not work yet :(, I am sure I missed some part, I already have a date field before in another example that works well before, but this one is a bit strange to me
[GanttChart.zip](https://github.com/microsoft/charticulator/files/5373899/GanttChart.zip)

**Comment by leilaetaatiprogram** [comment]
Oh Many Thanks!!!
