### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by SINCO-K** [microsoft/charticulator#336]
hi, I tried to make the sample on your gallery but it not working at all, I chose this sample (https://charticulator.com/gallery/world_population_2017.html)

**Comment by zBritva** [comment]
@SINCO-K Could you describe details or share screenshots of your results of building the chart?

Any detailed information can help figure out the reason of problem.

Thanks!

**Comment by SINCO-K** [comment]
Dear, Please find the attached snapshot of my build. 
<img width="898" alt="Test funnelChart" src="https://user-images.githubusercontent.com/71271420/95726137-36860780-0c81-11eb-89d1-cdc35ba2927d.PNG">

**Comment by zBritva** [comment]
It seems, you need to bind rectangle to point in axis:

![image](https://user-images.githubusercontent.com/10897951/95727665-266f2780-0c83-11eb-8164-2adb30b179a2.png)

**Comment by SINCO-K** [comment]
I did it, but no change the same problem
<img width="896" alt="Test funnelChart2" src="https://user-images.githubusercontent.com/71271420/95728434-2f142d80-0c84-11eb-8b6f-40a4760c8282.PNG">

**Comment by nadiafank** [comment]
Hi SINCO-K, 
can you check these points in your chart?

![Chart Pyramid](https://user-images.githubusercontent.com/1250376/95778709-f34f8700-0cc8-11eb-836b-e18bc402eac8.jpg)

**Comment by zBritva** [comment]
@SINCO-K Please review the docs about data driven guides (in docs you can find links to short video tutorial too):
https://charticulator.com/docs/user-interaction.html#data-driven-guides

You need to bind the rectangle corner to guide on axis:

![binding_marks](https://user-images.githubusercontent.com/10897951/95880677-6ec03f80-0d80-11eb-9da8-3a46af7c1ec2.gif)

**Comment by bongshin** [comment]
I'm closing this issue because there is no further discussion.
