### ISSUE TITLE
Scales do not adjust accordingly after changing data type

### ISSUE THREAD

**Issue by snapper911T** [microsoft/charticulator#339]
The "Position" field in my example contains numerical values. When I change this field to "categorical" I would expect the color scale when applied to an object to also change to a separate color for each value. IT maintains a continuous or diverging color pallete as if it was still numerical.
![Screenshot (1029)](https://user-images.githubusercontent.com/43861167/96216010-33667200-0f34-11eb-940f-6907b9934b74.png)

**Comment by zBritva** [comment]
You need to change the type not a kind.

![image](https://user-images.githubusercontent.com/10897951/96269685-5a27b580-0fd3-11eb-885a-44a1f6c2ea2e.png)

**Comment by snapper911T** [comment]
still not working for me
![image](https://user-images.githubusercontent.com/43861167/96286945-021e8e00-0f96-11eb-8c91-bbddc637d6a0.png)

Check out my .CHART file:
[data2example.zip](https://github.com/microsoft/charticulator/files/5393178/data2example.zip)

**Comment by zBritva** [comment]
Did you recreate the scale? (Hold the Shift button on drag & drop column to fill attribute)

**Comment by snapper911T** [comment]
Yes, I tried from scratch. No scales created yet. Change type to categorical then dragged to fill...same result :(
Also tried shift click and drag...

**Comment by snapper911T** [comment]
as @zBritva mentioned the issue was I did not change the data type when importing the dataset. Works now.

Example:
![image](https://user-images.githubusercontent.com/43861167/96292466-241c0e80-0f9e-11eb-9697-5f10e8bf5487.png)
