### ISSUE TITLE
Live data

### ISSUE THREAD

**Issue by aborruso** [microsoft/charticulator#346]
Hi,
is there a way to set a date remote URL, to have a live chart a chart that automatically updates as the data changes?

charticulator is really a great project, thank you

**Comment by zBritva** [comment]
No, Charticulator is not designed for that. As option you can export your chart as Power BI Visual and use [Data refresh in Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-data)

**Comment by aborruso** [comment]
It would be a really great feature.

Thank you
