### ISSUE TITLE
PBI Small Multiples feature in PBIVIZ 

### ISSUE THREAD

**Issue by snapper911T** [microsoft/charticulator#374]
Now that Power BI has a small multiples option for native visuals could we use that feature with a Charticulator visual in PBI?
I know there is "Nested Charts" but it is somewhat broken and has limitations currently. I feel like leveraging the small multiples component on top of a Charticulator viz may be a better solution??

https://twitter.com/i/status/1339049071852470272

**Comment by zBritva** [comment]
No, visuals created by Charticulator are **custom** visuals of Power BI, and they have difference from core visuals. It's feature of core visuals, not an API for visuals. Only improving the nested charts can be solution.
