### ISSUE TITLE
Status after major Power BI update

### ISSUE THREAD

**Issue by santiactis** [microsoft/charticulator#383]
Hi all,
First of all, thank you for your amazing work!
I was wondering if you had any information on how the custom visualizations compatibility works after a major Power BI update. My main concern is that some visualizations may break after that kind of update. Any insight would be greatly appreciated!

**Comment by zBritva** [comment]
Hello,
Power BI Visuals depends on API version. Charticulator uses [API 2.1.0](https://github.com/microsoft/charticulator-extensions/tree/master/powerbi-visual-builder/api/v2.1.0 ) on exporting charts as Power BI Visual.

New versions of Power BI Desktop and Services supports old visual API, and old visuals should work with the latest version and upcoming versions of Power BI too.

You can face with the problem after updating visual API version of Charticulator, if your Power BI Desktop is old and doesn't support new visual API.

If you still have questions about Power BI visuals, you can [contact with Power BI visuals support team](https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-faq#how-to-get-support) or ask question in [community form](https://community.powerbi.com/)
