### ISSUE TITLE
tooltip not showing for summarized values

### ISSUE THREAD

**Issue by nartabaza** [microsoft/charticulator#385]
I made a simple bar chart using Charticulator but I can't get the usual tooltip to work. It only shows up when I set the field to "Don't summarize", which is useless anyway because it just gives a list of all the values.
Is there something specific I need to do in Charticulator to get the tooltip working properly?

**Comment by zBritva** [comment]
@nartabaza thanks for reporting, the fix is coming

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 2.0.0).
