### ISSUE TITLE
Charticulator wont open properly in PowerBI

### ISSUE THREAD

**Issue by kwheeler92** [microsoft/charticulator#407]
For some reason, my graph loses a lot of its content when I load all of my data into Power BI.

This is what I created in Charticulator that I am trying to import:
![load1](https://user-images.githubusercontent.com/78817459/107409412-c160fc80-6ad1-11eb-93ea-2ad17dd84896.JPG)

This is what I see when I load the files into powerBI

![load2](https://user-images.githubusercontent.com/78817459/107411109-c45cec80-6ad3-11eb-97b7-400c6be58cd8.JPG)

These are my nodes, which work just fine in charticulator:

![load3](https://user-images.githubusercontent.com/78817459/107411255-efdfd700-6ad3-11eb-932e-ac21e91549b9.JPG)

These are my links, which also work just fine in charticulator:
![image](https://user-images.githubusercontent.com/78817459/107411352-05550100-6ad4-11eb-99d7-609705dff5ae.png)

I cant find a solution. Any help is appreciated.

**Comment by zBritva** [comment]
@kwheeler92 Could you share tables relations in Power BI? Also ensure that "Show items with no data" is enabled columns

**Comment by kwheeler92** [comment]
id is linked to source_id
![image](https://user-images.githubusercontent.com/78817459/107419884-e78c9980-6add-11eb-99e8-af0947876833.png)

Enabling show items with no data got me here:
![image](https://user-images.githubusercontent.com/78817459/107420206-42be8c00-6ade-11eb-871b-72bd59b468fa.png)

**Comment by kwheeler92** [comment]
id, column position, and strength are set to whole numbers, while the rest of the columns are set to text. Not sure if that will make a difference. 

Do you know if there is some setting in power bi that allows you to manually or automatically update data similarly to the formula workbook calculation in excel?

I created a hierarchy between the source_id and target_id under links. That didn't fix the problem, but when I deleted that suddenly the links appeared. 

![image](https://user-images.githubusercontent.com/78817459/107421754-f7a57880-6adf-11eb-9d53-3d5afb103920.png)

**Comment by kwheeler92** [comment]
I also have everything set to "Don't summarize"

**Comment by zBritva** [comment]
@kwheeler92 sorry for late reply, you need to merge two tables in Power Query Editor:

![image](https://user-images.githubusercontent.com/10897951/107945780-2a98b200-6fa1-11eb-8bf0-c8d23c9b0123.png)

The result:

![image](https://user-images.githubusercontent.com/10897951/107945841-4439f980-6fa1-11eb-9768-b6ca5bb0ab81.png)

"Show item with no data" and "Don't summarize" are enabled.

But I fount issue in code, you need to wait until fix will be deployed.

**Comment by zBritva** [comment]
It seems there is bug in visual part of charticulator, after assign aggregated column into primary key field bucket it renders chart as expected

![image](https://user-images.githubusercontent.com/10897951/108077372-820c5000-707d-11eb-9a32-00d9d67bbd83.png)

**Comment by bongshin** [comment]
This is now documented on the Charticulator website in [the Chart with Links section within the Power BI Tips page](https://charticulator.com/docs/power-bi-tips.html#chart-with-links).
