### ISSUE TITLE
Decimals Are Stripped from Numeric Fields

### ISSUE THREAD

**Issue by dm-p** [microsoft/charticulator#415]
**Describe the bug**
On importing a CSV, decimal values are stripped of their decimal point  and these are parsed as whole numbers, e.g. `2.38` is parsed as `238`.

**To Reproduce**
Verified on latest commit (262fe81)
1. From the New screen, import a CSV file containing decimal values.
2. Observe the preview in the pane.

**Expected behavior**
Decimal numbers should be imported as-is.

**Screenshots**

Example of raw CSV in Excel (right) vs. import in Charticulator (left)

![image](https://user-images.githubusercontent.com/10572054/107887207-4b451580-6f69-11eb-9d68-5c5401035a3c.png)

[driving.zip](https://github.com/microsoft/charticulator/files/5978415/driving.zip) (CSV doesn't seem to be permitted, so have zipped-up. Format is UTF-8 CRLF)

**Comment by dm-p** [comment]
I've tracked this down to [here](https://github.com/microsoft/charticulator/blob/262fe8133eed58be67ac91655d7ffb8e397310d4/src/app/application.tsx#L102), and looks like my store's `localeFileFormat` is getting set to treat `,` as the decimal rather than `.`

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 2.0.0).
