### ISSUE TITLE
How to Setup Power BI Relationships for Data and Links CSV Files

### ISSUE THREAD

**Issue by donaldsewardjr** [microsoft/charticulator#426]
I have exported a chart to Power BI but I am not certain how to setup relationships in Power BI to "mirror" what Charticulator does with the data and links files. The links file contains a "source_id" and "target_id" column, but only one of these columns can be mapped to the "id" column in the data file.

Attached are the csv files, pbix, and chart template.

[sankey chart objects.zip](https://github.com/microsoft/charticulator/files/6014037/sankey.chart.objects.zip)

**Comment by zBritva** [comment]
[There is documentation](https://docs.microsoft.com/power-bi/transform-model/desktop-many-to-many-relationships) of Power BI Desktop about Apply many-many relationships. You need to select `id` in main table and `source_id` in links table

**Comment by donaldsewardjr** [comment]
Thanks for the reply. **My data model is already setup** as you suggested and it isn't working (the pbix file was attached to my post).

Current Power BI relationship:
data.id > links.source_id

When I drag the source_id and target_id into the custom visual's data fields it doesn't render the chart correctly. It only renders the "source" side of the custom visual. 

If I switch the Power BI relationship to:
data.id > links.target_id

it then renders only the target side. I would think that both the source_id and target_id would somehow need a relationship...

**Comment by zBritva** [comment]
Did you enable "Snow items with no data" and "Don't summarize" for all columns in the visual? [There is](https://github.com/microsoft/charticulator/issues/407) related question

**Comment by donaldsewardjr** [comment]
You fixed it! Thank you for the quick replies and the solution. "_Don't summarize_" was already set but the "_Show items with no data_" wasn't checked. Sorry, I didn't find the similar issue when searching.

The following fields needed to be set to "_Show items with no data_": `id`, `name`, `value`, `group`.

<img width="1614" alt="fixed" src="https://user-images.githubusercontent.com/62261379/108610373-36221980-73a3-11eb-8780-fc31a54c2537.png">

**Comment by donaldsewardjr** [comment]
I know this is asking for a lot... but is there anyway to be able to click on any of the links themselves to filter: for example `red-underperformed`? I realize this issue is resolved, just figured I would ask real quick...

**Comment by zBritva** [comment]
This feature isn't supported

**Comment by donaldsewardjr** [comment]
Gotcha, thanks again for your prompt replies. This app is incredible.

**Comment by bongshin** [comment]
This is now documented on the Charticulator website in [the Chart with Links section within the Power BI Tips page](https://charticulator.com/docs/power-bi-tips.html#chart-with-links), and the requested feature is filed as a separate issue.
