### ISSUE TITLE
Data Axis not updating to represent input data

### ISSUE THREAD

**Issue by mahkrika** [microsoft/charticulator#485]
Potential bug on the Data Axis option.

In the below image I have two segments. The first is a basic plot where the y axis uses _avg(dataPoints)_ and automatically sets the range of 300-600. The second segment has a Data Axis in a different glyph. This is also set to use _avg(dataPoints)_ for the y axis. It also automatically sets the range of 300-600. 

![image](https://user-images.githubusercontent.com/60879262/113875306-87009c80-97ae-11eb-9772-060d5688c867.png)

All works ok until the dataset is changed. At this point the first segment updates the axis to show a range of 30-150. The second segment that uses the Data Axis in a glyph does not update, despite being based on the same _avg(dataPoints)_ formula. The range remains as 300-600. This causes a problem because when it passed to PowerBI the datapoints that are based on the Data Axis will not display as they are on different scales.

![image](https://user-images.githubusercontent.com/60879262/113875684-ed85ba80-97ae-11eb-949c-9ae47f39d3cd.png)

In order to get the Data Axis to update to match requires clearing the Data Axis and dragging the dataPoints set back in to refresh the range values. I expected it to update automatically as it does in the other segment.

**Comment by zBritva** [comment]
It's not supported for editor, when you replace dataset in editor, it updates only plot segments axes.

if you didn't disable it on export to the visual, in Power BI visual data axis object range should be updated, when you assign data to visual with new range.

Could you share your visual file, it is not private?

**Comment by mahkrika** [comment]
Oh I see; I apologise, I didn't understand that. Repeating the process with a simpler dataset has shown that whilst it doesn't update in the editor it does update in Power BI visual, sorry for the misunderstanding. My issue with updating in the Power BI visual was a different (unconnected) problem with ranges on datasets I think (filters were being applied to the main plot segment that were not applied to the Data Axis) - but this is my own problem.

Thanks for the quick response, much appreciated.

**Comment by zBritva** [comment]
Anyway, we have case for improving Charticulator. Thanks!

**Comment by bongshin** [comment]
This issue is addressed in the latest deployment (Version 2.0.2).
