### ISSUE TITLE
Adding the Quantile function from D3.js is failing

### ISSUE THREAD

**Issue by MikeCarlo** [microsoft/charticulator#499]
**Describe the bug**
When adding a data expression to a Data Axis inside a Glpyh I can use the Min, Max, stdev functions, but I can't use the Quantile function

**To Reproduce**
1. add a data axis to a Glyph
2. Drag a data (number) column from the fields pane on to the Data Axis
3. the default function is avg( <somecolumn> )
4. Change the function to quantile( <SomeColumn> )
5. You get a Parse Error
![image](https://user-images.githubusercontent.com/25160592/115640157-e5b03500-a2db-11eb-9c38-8435a96ef15e.png)

**Expected behavior**
The quantile function would be parsed correctly.

**Screenshots**
see step 5 above.

**Software**
Using the Charticulator Power BI Custom Visual App

**Reference Link**
https://www.geeksforgeeks.org/d3-js-d3-quantile-function/

**Comment by zBritva** [comment]
Charticulator doesn't use d3 functions for expressions. (It uses d3.js for formatting data only)

It has own implementations. You can find the list of functions in source code:
https://github.com/microsoft/charticulator/blob/master/src/core/expression/intrinsics.ts#L130-L209

Unfortunately no any user documentation for that. 

@bongshin do we need to implement it?
