### ISSUE TITLE
Cannot Build on Win 10, Surface Book

### ISSUE THREAD

**Issue by brettforbes** [microsoft/charticulator#512]
I have a Surface Book, running Win 10, fully updated.

I have node v15.01 and npm v 7.11.1

Following your instructions i install yarn globally using npm, as administrator, no problems

I cd into the charticulator directory, and try to run  ```yarn build ```

The process errors out with the message module 'fs-extra' module not found, see screenshot below.

What am i doing wrong?

![image](https://user-images.githubusercontent.com/24556510/116363849-e8180f00-a846-11eb-94ef-48e1da6f036f.png)

**Comment by zBritva** [comment]
Did you call `yarn install`. Did you get any errors on installing packages?

**Comment by brettforbes** [comment]
Hi, that was quick, I did ```npm -g yarn``` under admin privileges, and it seemed to install correctly, then I followed the approach above

**Comment by zBritva** [comment]
no, I don't mean yarn package. Charticulator uses many packages. and one of them `fs-extra`.

you need to call `yarn install` int the root of project folder then call `yarn build` to build the project.

**Comment by brettforbes** [comment]
Following your suggestion, I attach below the result of the yarn install and build commands
![image](https://user-images.githubusercontent.com/24556510/116366516-b81e3b00-a849-11eb-8377-6d4a6850c01b.png)

**Comment by zBritva** [comment]
Why you call `yarn install` in one folder and `yarn build` in another?

**Comment by brettforbes** [comment]
aah, I thought I was meant to do yarn install in the root, and then yarn build in the charticulator directory. Is  this incorrect?

**Comment by zBritva** [comment]
Sorry, probably I explained it incorrectly. Call both command in the same directory where is `package.json` file

**Comment by brettforbes** [comment]
It works, it was total user error, by cd-ing to the charticulator sub-directoy, it installs perfectly with yarn install and then yarn build, no error messages.

Sorry about that, thanks
