### ISSUE TITLE
Data Axis Issue

### ISSUE THREAD

**Issue by jwoldham** [microsoft/charticulator#528]
The Web interface application is not allowing me to add Data Axis to Glyph.  I have tried three different browsers and two different computers and I cannot add a Data Axis to the Glyph

Should also mention that when I try to add a measure to the height attribute of my Glyph the entire visual in the glyph disappears. I am making sure that when I drag the data point to the Glyph, the Height attribute highlights in yellow indicating that I am dropping it in the appropriate place.

**Comment by jwoldham** [comment]
Should also mention that when I try to add a measure to the height attribute of my Glyph the entire visual in the glyph disappears.  I am making sure that when I drag the data point to the Glyph, the Height attribute highlights in yellow indicating that I am dropping it in the appropriate place.

**Comment by bongshin** [comment]
Thanks @jwoldham for reporting these issues, which were introduced by the latest deployment (on May 7th PDT). I reverted back to the previous version that does not have these issues. Sorry for the inconvenience this may have caused.
