### ISSUE TITLE
Html export is empty

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#545]
Describe the bug
I created a sankey chart in charticulator web and when I try to export it to html, it is empty.

To Reproduce
[Charticulator #7 Sankey chart.zip](https://github.com/microsoft/charticulator/files/6544601/Charticulator.7.Sankey.chart.zip)

![charticulator web](https://user-images.githubusercontent.com/19476550/119367424-37b8f180-bcb2-11eb-8cd9-88f8a82fbbd3.jpg)
![2021-05-24_17-04-59](https://user-images.githubusercontent.com/19476550/119367428-38ea1e80-bcb2-11eb-88ee-0d39a8d92af1.jpg)

Expected behavior
I was expecting to see the chart

**Comment by viera00** [comment]
I'm having the same issue .

**Comment by bongshin** [comment]
<img width="463" alt="image" src="https://user-images.githubusercontent.com/9288805/153049688-7103c7ea-1434-4426-bfb2-911c3d73c83f.png">
