### ISSUE TITLE
Conditional format (or color) links 

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#546]
**Is your feature request related to a problem? Please describe.**
I would like to be able to color the links on a sankey chart. I drop a color field but it didnt color, I could only color it with a fixed color using the color picker.

**Describe the solution you'd like**
Check the images attached for the desired effect

**Describe alternatives you've considered**
I tried using the user interface but no color was applied. Links > Attributes > Color

![charticulator web](https://user-images.githubusercontent.com/19476550/119367825-a433f080-bcb2-11eb-9477-c21bf9f20f95.jpg)
![rdeddit](https://user-images.githubusercontent.com/19476550/119367993-d1809e80-bcb2-11eb-8cc1-3b155778ef61.jpg)

**Comment by zBritva** [comment]
Links supports data binding from Links table only. If you try to assign color by using column from main table it will not work.

**Comment by ruthpozuelo** [comment]
Yes, I saw that. It would be great if it can be added.

**Comment by zBritva** [comment]
I don't think it is clever idea. In case when you have two nodes and one link, you must know from which nodes you need to take color for link? (from the first or from then second)

**Comment by ruthpozuelo** [comment]
The same way you specify what to link with what, you can also specify which color to use from one node to the other.  😊

**Comment by zBritva** [comment]
You can provide it in links table. Why you need it in main table.

**Comment by ruthpozuelo** [comment]
We are probably misunderstanding each other. 

Is it possible to color the links in charticulator? so, if I provide a color column in the links table, will they be colored as the example I show above?
I have no preference or opinion on how it is implemented, I just think it would be neat to be able to color links.

**Comment by zBritva** [comment]
If you provide values for color - yes.

https://charticulator.com/gallery/global_trade_of_natural_resources.html see example.

**Comment by ruthpozuelo** [comment]
I tried but no luck. 
Here is my file:
[Charticulator #7 Sankey chart - Copy.pbix.txt](https://github.com/microsoft/charticulator/files/6733123/Charticulator.7.Sankey.chart.-.Copy.pbix.txt)

and this is my attempt:
![link colors](https://user-images.githubusercontent.com/19476550/123792210-aa844080-d8e0-11eb-8a31-fcd1d2e233c6.gif)

**Comment by PBI-David** [comment]
I believe this can be closed now as the links can be coloured if you follow @zBritva's instructions: 
![image](https://user-images.githubusercontent.com/86846675/142081088-09ef89cf-3f61-4f21-bc3c-a5e614674f73.png)

**Comment by ruthpozuelo** [comment]
Maybe I need to redo it because it still wont color for me. My pbix file:
[Charticulator #7 Sankey chart.txt](https://github.com/microsoft/charticulator/files/7553609/Charticulator.7.Sankey.chart.txt)

**Comment by PBI-David** [comment]
I used your .pbix Ruth. 
Click remove what you currently have on the link. 
![image](https://user-images.githubusercontent.com/86846675/142181187-a31e31b1-d93e-442d-bea0-f97b1fabd7c7.png)

Click bind link and then target and choose your colours. 

![image](https://user-images.githubusercontent.com/86846675/142181322-c5f9bd99-c5c8-4e27-80a2-cd84de7d8c86.png)

**Comment by ruthpozuelo** [comment]
Oh! I see my mistake, i was using a field from the data bucket not the Links!
Thanks!

**Comment by zBritva** [comment]
@PBI-David , @ruthpozuelo maps "Color" from main table. It will not work. To Link object you can bind Links table columns only.

Limitation reason: 
1. Charticulator expression doesn't contains context for execution module.
2. Execution on expression with different tables (different context) gives different results.
3. **Default context for expressions in main table. And only for Link object is links table.**

So, when you bind expression `first(Color)` to links and if you don't have such columns in Links table, the result of executing expression is empty and no color.
