### ISSUE TITLE
Window out of scope and can not be moved in Power BI

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#549]
**Describe the bug**
When both the Glyph and layers are in full mode (or expanded) and I click on a symbol to scale it, the scale window is out of scope and I can not move it.
The only way to access it is to minimize the other panes.

**To Reproduce**
Add a symbol to the visual
Click on Symbol to access

**Expected behavior**
Be able to move the window to access it.

**Screenshots**
![Window out of scope and cannot be moved](https://user-images.githubusercontent.com/19476550/119675694-8d6dd500-be3d-11eb-9344-0f9e20a97959.jpg)

**Comment by zBritva** [comment]
In the visual version 1.0.5 on click scale binding scrolls Attribute panel to property before open the scale editor
