### ISSUE TITLE
Difficult to see the color picker when the default color is white

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#550]
**Describe the bug**
When the default color is white, is very difficult to see the color picker and it almost looks like you need to manually enter the color code.

**To Reproduce**
see image

**Expected behavior**
Maybe have an outline on the color box?

**Screenshots**
![color picker](https://user-images.githubusercontent.com/19476550/119676854-7d0a2a00-be3e-11eb-830a-0c35cae7121b.jpg)

**Diagnostic information**
If applicable, provide diagnostic information (you can get it by copying it to clipboard).

**Additional context**

**Comment by bongshin** [comment]
This issue is addressed in the latest deployment (on June 24, 2021).
