### ISSUE TITLE
Export charticulator from Power BI

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#553]
**Is your feature request related to a problem? Please describe.**
Be able to export a charticulator viz made in power bi so it can be imported in the web version or another power bi report.

**Describe the solution you'd like**
Have the same export capabilities a charticulator web.

**Comment by zBritva** [comment]
You can export template from web version and visual version too. 
![image](https://user-images.githubusercontent.com/10897951/123473811-c1394780-d601-11eb-9a4a-c0cbf6cd2e0b.png)
And import into another instance of visual.
![image](https://user-images.githubusercontent.com/10897951/123473866-d9a96200-d601-11eb-8835-b1c4496b8e20.png)

**Comment by ruthpozuelo** [comment]
Yes, I found that, but still it would be great to be able to export as an image, html or chart.

**Comment by zBritva** [comment]
@ruthpozuelo visuals have limitations on exporting the something from the visual in Power BI Desktop. Technically it is impossible to show user save file dialog.

**Comment by zBritva** [comment]
@ruthpozuelo visuals have limitations on exporting the something from the visual in Power BI Desktop. Technically is is impossible to show user save file dialog.
