### ISSUE TITLE
Ability to Define Manual Nominal Scales (and Remove Unused Ones)

### ISSUE THREAD

**Issue by dm-p** [microsoft/charticulator#557]
**Is your feature request related to a problem? Please describe.**

The ability to data-drive attributes such as visibility is really powerful, when combined with measures in Power BI, and has a lot of potential for dynamic formatting. However, if I want to try and prescribe behaviour based on values that aren't in the dataset, then this is not possible.

Charticulator's scale assignment for nominal categories in data-vound attributes seems to be derived based on the available distinct values of a field for the dataset, so I must have these values present in order for the scale to make them available for me to use in assignment for things like conditional filtering.

An example of this is if I want to calculate a data point's significance, and show or hide a mark subject to this value. My measure *might* return one of the following:

* `~` (No indicator)
* `H` (High value)
* `L` (Low value)
* `E` (End data [point)

However, I can only bind the scale to values present in the dataset at design time:

![image](https://user-images.githubusercontent.com/10572054/120248157-2f704000-c2ca-11eb-9c67-8c81608e0f39.png)

If I mock them up or remember to include glyphs that have all distinct values in the scale, I can sometimes get this to work when I create the data bindings. However, if I have a situation in my example where the high and end values overlap, I lose the `E` value from my dataset so that the scale does not know about it, e.g.:

![image](https://user-images.githubusercontent.com/10572054/120248255-86761500-c2ca-11eb-9fec-256ecac2c567.png)

If I then save the design, the fill value for `E` is lost and I then need to manually add it back. Sometimes it is unrecoverable and the scale logic does not resolve it again, so I then need to delete my design, as I cannot manually delete a scale that Charticulator reserves for that field's value... or I can shift-add a new scale and have the old one lying around orphaned. I can delete an assignment from a scale... just not the scale itself.

**Describe the solution you'd like**

Ideal solution would be that I can:

* Manually add a scale, and specify additional values that are not bound to specific data in the dataset (but could be, based on my business logic)
* Flag this so that it does not recalculate (much like turning off auto min or auto max does this for linear and temporal axes/scales)
* Be able to manually delete a scale so that there aren't erroneous ones lying around in the design

**Describe alternatives you've considered**

I currently manually edit the `scale` in the `.tmplt` file, which is not ideal.

**Comment by bongshin** [comment]
This issue is addressed in version 1.1.2.
