### ISSUE TITLE
Image URL not visible

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#559]
The UI to bind an image to a text, if the text is too long it wont show making difficult to guess what image to bind to each text. 

It is enough if hovering over the text shows the entire field.

See image below:
![image url not visible](https://user-images.githubusercontent.com/19476550/120484732-a6353800-c3b3-11eb-85f9-c9ad6ff67903.jpg)

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.1.2).
