### ISSUE TITLE
Boolean Scales Don't Persist in Power BI When Navigating Back to Report

### ISSUE THREAD

**Issue by dm-p** [microsoft/charticulator#561]
## Describe the bug
If I use a boolean scale in Power BI to toggle a mark's visibility, it works in the designer, but the data binding is lost when I return to my report. 

## To Reproduce

This is an attempt to work around the current limitations requested in #557, so I'm using measures with 0/1 values so that I can define boolean expressions based on range rather than an explicit nominal value.

1. In the editor, add the field to the visibility condition
2. Specify a valid boolean condition, e.g.:
![image](https://user-images.githubusercontent.com/10572054/120545820-39697e80-c443-11eb-973e-288cf41f41c8.png)
3. Save the chart and return to the report.
4. The visibility condition is removed and all labels are shown.
5. Upon re-opening the editor, the scale has been reset by Charticulator, e.g.:
![image](https://user-images.githubusercontent.com/10572054/120546179-aa109b00-c443-11eb-99b7-94df3501a31b.png)

If I use a nominal category, e.g.: `Y` / `N`, then this works as expected, but I cannot always guarantee that these values will be present in the visual dataset at design time.

A workaround is that I *could* create a measure that sets the text to `""` instead, but this is not desirable.

## Expected behavior

Scale should be preserved, so that logic works in the report as per the design view.

## Screenshots

Setting the scale in the editor (and resulting successful effect on the chart)

![image](https://user-images.githubusercontent.com/10572054/120545753-25be1800-c443-11eb-9b74-c00553aefe4d.png)

Chart in report, after saving:

![image](https://user-images.githubusercontent.com/10572054/120546007-75044880-c443-11eb-9fd7-82da46f71cf4.png)

Editor, after re-opening:

![image](https://user-images.githubusercontent.com/10572054/120546458-0673ba80-c444-11eb-8543-15c6c3b7ec94.png)

**Comment by zBritva** [comment]
@dm-p The issue was fixed in the visual version 1.0.5. Could you confirm? Thanks!

**Comment by dm-p** [comment]
Hi @zBritva - thanks for the heads-up. Can confirm this is now working in 1.0.5! 

![image](https://user-images.githubusercontent.com/10572054/125208083-92e78780-e2e4-11eb-8acf-e7e62e8b2ae9.png)
