### ISSUE TITLE
Sort by another column

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#563]
**Is your feature request related to a problem? Please describe.**
I am not sure if this is possible already, i havent found a way to do it. I would like to sort the axis by another column.

**Describe the solution you'd like**
I am trying to sort the X axis by another column to sort it properly.

**Describe alternatives you've considered**
I have tried to sort the chart and to sort the axis but havent succeeded in doing that.

**Additional context**

![sort axis](https://user-images.githubusercontent.com/19476550/120937745-77022c00-c70f-11eb-85a5-4f8d83c72d2c.jpg)
![sort axis dialogue](https://user-images.githubusercontent.com/19476550/120937747-78335900-c70f-11eb-995f-0baf61d17767.jpg)

**Comment by dm-p** [comment]
Hi Ruth,

If the axis is bound to a column, I don't think there's a specific ability to sort by another column (I think there's some in-built logic with months but that's about it).

In the case of 'known' categories, it's possible to drag sort them to a suitable position. I've done a crude mock-up of the chart and reproduced for you - here's a GIF:

![Drag Sort Category](https://user-images.githubusercontent.com/10572054/121626174-0ec59880-cac9-11eb-85d6-8acb9d716abe.gif)

Ideally, we should be able to supply another column in these situations, but hopefully this will give you something in the way of a workaround for now.

Regards,

Daniel

**Comment by ruthpozuelo** [comment]
That is really useful Daniel, Thanks!!
And looking at your chart, I might have overdone mine a little!! Will give it a new go ;)

**Comment by dm-p** [comment]
Glad it could help you out!

**Comment by bongshin** [comment]
See https://github.com/microsoft/charticulator/issues/890 and https://github.com/microsoft/charticulator/issues/704.
