### ISSUE TITLE
Measures Returning Blank Values Cause Power BI Visual to Not Map Data Correctly on update()

### ISSUE THREAD

**Issue by dm-p** [microsoft/charticulator#565]
## Describe the bug
If the Power BI custom visual's data view contains blank values for a field in a row, the visual does not map the data and treats it as though no data is present. This prevents further editing and updates.

## To Reproduce
1. Add a measure containing `null`/`(blank)` values to the dataset.
2. Attempt to edit the visual.
3. The visual retains the landing page and doesn't open the advanced editor (as per screenshots below).

Adding `0` to the measure, to make the resulting value non-`null` will cause the visual to render correctly, but this is not intuitive for end users to rectify.

As there's no visibility of the custom visual code, I can take a guess at the method mapping the data view to the visual is erroring-out (or handling a parse error) and falling through to an 'empty dataset' state.

In the web application, if Charticulator detects the column as a `number`, it will pad `null` values with zeroes, e.g.:

![image](https://user-images.githubusercontent.com/10572054/121116857-4cc58100-c86b-11eb-9e05-41b1006756b3.png)

(Note that the fields were exported without formatting so that the web app didn't treat them as strings)

## Expected behavior

I would expect the data view to map correctly and treat the datset as valid.

Whilst `null` should be a valid state for measures, at a minimum I would expect the visual to map `null`/`(blank)` values as `0` for numbers or text values as `""` rather than treating the visual as having no data (as per the web app).

## Screenshots
* Visual advanced editor, with data (but no editor):
![image](https://user-images.githubusercontent.com/10572054/121117043-9f06a200-c86b-11eb-9410-40ed67d818a8.png)

* Visual data view for above scenario:
![image](https://user-images.githubusercontent.com/10572054/121117133-c198bb00-c86b-11eb-898f-7cd07792510b.png)

* Visual after 'fixing' the `(blank)` result to `0`:
![image](https://user-images.githubusercontent.com/10572054/121117758-cad65780-c86c-11eb-8cda-ecec748ee0b4.png)

**Comment by ruthpozuelo** [comment]
ohhh, this has happened to me a mission times and have never understood why. Thanks!

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.0.5).
