### ISSUE TITLE
Unable to clear Charticulator canvass

### ISSUE THREAD

**Issue by steved-MarketGrunt** [microsoft/charticulator#568]
Hi,
I'm trying to use Charticulator in Power BI. However, when I open the visual for editing, there is data from a trial I did with charticulator.com in the data section. I hope the screen shot below better describes the issue.
![image](https://user-images.githubusercontent.com/42726129/121767152-dd68cd80-cb99-11eb-9097-095b21dddb10.png)

How do I clear the remnant data please.

**Comment by steved-MarketGrunt** [comment]
I think I've resolved the problem. I removed the calculation group in the model and charticulator started to work again.

**Comment by zBritva** [comment]
@steved-MarketGrunt Could you give details about dataset?

What dataset did you used? 
I try to reproduce the bug to fix, but I can't find reason

**Comment by steved-MarketGrunt** [comment]
@zBritva I came across the same issue later. I think the dataset of Month, City, Value appears when charticulator is unable to categorize a field from the underlying dataset. Which begs the question of what Fields and measures will charticulator accept?

**Comment by zBritva** [comment]
@steved-MarketGrunt it should support all data types. The current version doesn't support blank values only. Do you have blank values in your dataset in this case (`TOD Total Cases FYTD`)?

**Comment by steved-MarketGrunt** [comment]
@zBritva Thanks for the heads up on that, Yes, there are blank values and when removed it works as expected. Will 0 be treated as the same as blank?

**Comment by zBritva** [comment]
@steved-MarketGrunt the visual 1.0.5. was published. Now blank/null values should handle as 0 for numerical data and as empty string for string data.
