### ISSUE TITLE
Cant save changes in Power BI visual

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#569]
**Describe the bug**
When I create visuals using Power BI charticulator, sometimes, it wont save the changes.

**To Reproduce**
1. I try to change the legend position
2. I create a guide to hook it to
3. I snap the legend to the guide
4. click save
5. all changes are lost.

**Expected behavior**

**Screenshots**
I expect the legend to stay where I put it after I save.
![cant save changes](https://user-images.githubusercontent.com/19476550/121886203-6eb07f00-cd15-11eb-8d96-b45c08ed3ed2.gif)
[Charticulator #10 Lollipoll.zip](https://github.com/microsoft/charticulator/files/6647980/Charticulator.10.Lollipoll.zip)

**Diagnostic information**
If applicable, provide diagnostic information (you can get it by copying it to clipboard).

**Additional context**

**Comment by zBritva** [comment]
It's known issue. You need to drag and drop the guide to change position after creating. It should set property for guide.

**Comment by ruthpozuelo** [comment]
oh, I got you! So, first, I set the position (like shown in the gif) and then I drop the guide. It works, thanks.
