### ISSUE TITLE
Add tutorial to show how to add error bars/confidence intervals

### ISSUE THREAD

**Issue by mrjamesperry** [Microsoft/charticulator#57]
I read the paper Charticulator: Interactive Construction of Bespoke Chart Layouts and Figure 9 states it was created in Charticulator.  I can't reproduce it.  
Would it be possible to add a tutorial to show how to do this?  Being able to add error bars to a simple bar or line graph is a missing element of PowerBi and limits its use for statistical visulisation.  Using Charticulator to create a custom visual to do this would be great!

**Comment by bongshin** [comment]
Added a new tutorial, "Bar Chart with Error Bars"

**Comment by mrjamesperry** [comment]
Many thanks, I'm almost there and once the PowerBi custom visual output is released this will solve an issue we've been grappling with for ages.  The potential for custom visual creation is very exiting! 
I've read the tutorial and all the other help and am getting stuck on the graph.  Following your guide, using this dataset below

Time period | Value | Lower CI 95.0 limit | Upper CI 95.0 limit
-- | -- | -- | --
2010/11 | 5.786 | 5.732 | 5.840
2011/12 | 5.266 | 5.215 | 5.318
2012/13 | 5.335 | 5.284 | 5.387
2013/14 | 4.594 | 4.547 | 4.642
2014/15 | 4.541 | 4.494 | 4.589
2015/16 | 4.477 | 4.431 | 4.524
2016/17 | 4.581 | 4.534 | 4.627

I am getting the following result. Essentially the x axis is duplicating values and I can't work out how to correct.
![charticulator](https://user-images.githubusercontent.com/28100175/46010085-560d6000-c0b9-11e8-8711-904bc190a99d.png)

**Comment by mrjamesperry** [comment]
Issue fixed with last night's update - now playing with PowerBI customviz export.  Great work - thanks!
