### ISSUE TITLE
Nested Chart option is missing in the Micosoft Charticulator Visual 

### ISSUE THREAD

**Issue by DVLNarayana** [microsoft/charticulator#575]
I imported Microsoft Charticulator Visual (v1.0.3) from Power BI Visuals App Source.

I am unable to find the Nested Chat in Microsoft Charticulator Visual 
I observed difference between Microsoft Charticulator Visual and [https://charticulator.com/](https://charticulator.com) In Microsoft Charticulator Visual Nested chart Option is missing.

**Comment by zBritva** [comment]
Nested chart editor not supported in the visual for now

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.1.0).
