### ISSUE TITLE
Nested Charts Not Working Correctly

### ISSUE THREAD

**Issue by ppm321** [microsoft/charticulator#576]
When I add a nested chart to the Glyph and then choose "Edit Nested Chart", a new window opens but it does not say "Save Nested Chart" at the top and the data fields return to the default ones.  It doesn't seem to be linked to the parent chart.

**Comment by baker339** [comment]
I am also having this issue. Have you heard any update on this? @ppm321

**Comment by bongshin** [comment]
This issue is addressed in the latest deployment (on June 23, 2021).
