### ISSUE TITLE
Scrollable Charts

### ISSUE THREAD

**Issue by ppm321** [microsoft/charticulator#577]
Please add the ability to make charts from the Website and the Power BI visual scrollable (or a way to page through a fixed number of rows/glyphs displayed at a time.

**Comment by ruthpozuelo** [comment]
+1 
When the charts have too much information, charticulator clumps everything in the small space making it unreadable.
Example:
Few data points:
![image](https://user-images.githubusercontent.com/19476550/122656579-22719e80-d15c-11eb-96e1-2959211ebb60.png)
All data points:
![image](https://user-images.githubusercontent.com/19476550/122656582-2e5d6080-d15c-11eb-8add-bd2c7b7f0c15.png)

**Comment by bongshin** [comment]
This issue is addressed in the recent release (Version 1.1.1).
