### ISSUE TITLE
Text not showing in the same place in edit and visual mode.

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#584]
**Is your feature request related to a problem? Please describe.**
I dont know if this is a bug or I am doing something wrong, but when placing text on the edit view of power bi charticulator, it shows in one place in the edit mode and in another in view mode.

**Describe the solution you'd like**
This is how it looks in "edit" mode:
![image](https://user-images.githubusercontent.com/19476550/122749768-ffdfa280-d28d-11eb-8db6-225679ebe6d0.png)

and when I load it to power bi visual pane:
![image](https://user-images.githubusercontent.com/19476550/122749809-0e2dbe80-d28e-11eb-898a-ebad65571bfb.png)

**Describe alternatives you've considered**
I wanted to have a text box under each column, but wasnt able to place them there as they moved around even when I anchored it with guides.

**Comment by zBritva** [comment]
Did you anchor them to the guides?

![image](https://user-images.githubusercontent.com/10897951/122753758-60c1a780-d29b-11eb-98a9-2670984071ae.png)

**Comment by ruthpozuelo** [comment]
Yes, but it wont work:
![image](https://user-images.githubusercontent.com/19476550/122754783-61a30b00-d294-11eb-8005-1c016acd22fe.png)
 and in the visual:
 
![image](https://user-images.githubusercontent.com/19476550/122754815-6a93dc80-d294-11eb-92c4-92ca13fe70b8.png)

**Comment by zBritva** [comment]
The text box didn't align horizontally. In this case solver don't have constraint to align the textbox and can give any arbitrary value for x1 and x2 attributes of textbox

**Comment by ruthpozuelo** [comment]
ok, so it means it is not possible? If that is the case, can it be added?

**Comment by zBritva** [comment]
Could you share the template or chart file if it is not private?
Or give some details.
I see you use vertical guides and seems the text to aligned to them.

Where had you put the text and guides? I suspect the text on the chart and guides on the glyph.

**Comment by ruthpozuelo** [comment]
I am still learning charticulator, apologies if the bugs/ features are not such at times.

I dropped the guide and text to the chart. 

Here is my file: (pbix file so you get the data too)
[text issue.zip](https://github.com/microsoft/charticulator/files/6692264/text.issue.zip)

**Comment by zBritva** [comment]
1. I see you used one text box for all three texts.

In edit mode we have

![image](https://user-images.githubusercontent.com/10897951/122894928-51506600-d350-11eb-9ccf-9ac95db553a1.png)

there chart size is 441x489

But often visuals size is smaller than chart size in charticulator. And in this case Charticulator can adoptee the chart elements with new constraints (fir small size). Except font size of text. It's why your  text still have the same size. 

![image](https://user-images.githubusercontent.com/10897951/122895408-c15eec00-d350-11eb-9c0e-182946fad5e7.png)

The same problem you reported in https://github.com/microsoft/charticulator/issues/548

If you set the same size for the visual and chart it renders expected:

![image](https://user-images.githubusercontent.com/10897951/122895929-3d593400-d351-11eb-9af6-5de3830ee1ca.png)
Pay attention to text position (it's from mid of grey bar to mid to red bar) in editor

and the chart in the view mode:
![image](https://user-images.githubusercontent.com/10897951/122896191-7e514880-d351-11eb-8c03-2c02a2795ed4.png)

2. If you want to put text under each bar, I think it's better if you put 3 text objects aligned by bars. And two lines or two texts with dashes.

See attached template:
[TextAlignment.txt](https://github.com/microsoft/charticulator/files/6692891/TextAlignment.txt) (rename file extension to `tmplt`)

![image](https://user-images.githubusercontent.com/10897951/122898386-7eeade80-d353-11eb-9894-0756d005cfe0.png)
![image](https://user-images.githubusercontent.com/10897951/122898411-83af9280-d353-11eb-9941-c540f5264562.png)

This template more responsible to varied sizes of the visual.

I used conditional visibility with three different scales (**it is important!**) to hide or show text objects:

![image](https://user-images.githubusercontent.com/10897951/122898904-f456af00-d353-11eb-87ac-a158683003b7.png)

**Comment by ruthpozuelo** [comment]
Yes, sorry! The file I sent you did not have my three text boxes attempt on it.

and thanks a million for the charticulator lesson, really good to know.

I hope it is ok to keep posting here features and “bugs”. If there is any other place where it would make more sense, please let me know and thanks for your patience with me.

BTW, I only post here when I find something odd or something missing, but I want to say that charticulator is the best thing that has happened to power bi in years!! I love what you have done and I hope you will continue to develop it further. It gives me super viz powers and I love it. Thanks a million!
