### ISSUE TITLE
Guides and text on glyphs need to have values manually added on attributes to be placed on a fixed position

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#586]
**Describe the bug**
When I try to fix a guide or text on a glyph, I drop it on the glyph area where I want it. If I dont add an attribute to the guide or text, it changes position. Only when I add it manually it will stay in place.

**To Reproduce**
1. Drop a guide on glyph
2. Save visual in power bi 
3. Guide moves out of position.

**Expected behavior**
I would expect the guide to take the position I "specify" when I drop it on the glyph, but that does not seem to work. Only when I add the position manually it will stay in place.

**Screenshots**
![text and guides cant not be set until a value is given](https://user-images.githubusercontent.com/19476550/122919099-266e0e00-d360-11eb-8685-4fb46fad799c.gif)

**Comment by zBritva** [comment]
Duplicates https://github.com/microsoft/charticulator/issues/201
