### ISSUE TITLE
Rotate symbols

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#589]
**Is your feature request related to a problem? Please describe.**
I was thinking using a triangle symbol to create a comet chart, but I would need to rotate it in order to work and it doesnt seem possible.

**Describe the solution you'd like**
Be able to free rotate symbols in the attribute pane. Both hardcoded numbers and data driven.

**Describe alternatives you've considered**
I am trying to create this:
![image](https://user-images.githubusercontent.com/19476550/123219682-75858180-d4cd-11eb-84f4-85501f6ebdbc.png)
and one way to do it could be to rotate this:
![image](https://user-images.githubusercontent.com/19476550/123219436-30f9e600-d4cd-11eb-8879-f445a7a65d5c.png)
Although i am not sure it that would work, it still would be useful to be able to rotate symbols.

**Comment by dm-p** [comment]
This is a request that would open up many new use cases, particularly for using symbols for producing IBCS-compliant charts. For instance the fixed orientation of the triangle makes it ideal for using it as a target indicator on a bar chart, but not possible for a column chart.

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.1.2).
