### ISSUE TITLE
Possibility to edit a .tmplt directly in power bi

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#593]
**Is your feature request related to a problem? Please describe.**
If I build a chart in charticulator web, export it as a .tmplt and import it in power bi, the template file is not editable in power bi, i have to import it again in charticulator web to see how it was built.

**Describe the solution you'd like**
I would like to be able to edit .tmplt files directly in power bi.

**Describe alternatives you've considered**
I edit them now in the web, but that means that i need to export the data too.

Edit button not available for template files in power bi:
![image](https://user-images.githubusercontent.com/19476550/123659203-b6b1c480-d832-11eb-8f6d-23de80e14b2a.png)

**Comment by zBritva** [comment]
Did you export the chart as "Power BI Custom Visual"?

![image](https://user-images.githubusercontent.com/10897951/123659504-6ee36b00-d83b-11eb-8428-2412ad006338.png)

This version of visuals doesn't contain editor part of code.

You can import your template into [Appsource version of Charticulator](https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA200002793?tab=Overview)

1. Enabling editor for old approach is complicated and will confuse users (Old approach generates different GUIDE for created visual). 
2. When Charticulator starts to support new feature of bug fixes users must update each visual manually by exporting the chart as visual and import into **all reports** and replace **all visual** instances.

**Comment by ruthpozuelo** [comment]
Ok, so I can edit visuals that have been exported as custom visuals, but I can not edit templates. 
Got you. Thanks!
