### ISSUE TITLE
Quantile function has been added to GitHub Repo but not available in Desktop Custom Visual

### ISSUE THREAD

**Issue by MikeCarlo** [microsoft/charticulator#595]
**Description of Bug**
It seems like the quantile function has been added to the GitHub repo. but when I try to use this function in the Power BI desktop Custom Visual, I get an error.

Code listed in Charticulator GitHub found in [this file](https://github.com/microsoft/charticulator/blob/d253f4b0998473d24b794c861393aad40def1766/src/core/expression/intrinsics.ts).    

![image](https://user-images.githubusercontent.com/25160592/123993524-1bcffc00-d992-11eb-997e-4313d241f20d.png)

Image from Charticulator Custom Visual in Power BI desktop
![image](https://user-images.githubusercontent.com/25160592/123993808-63568800-d992-11eb-83e0-e2f4b4957536.png)

or all lower case:
![image](https://user-images.githubusercontent.com/25160592/123994241-cc3e0000-d992-11eb-98da-664bfd4b2783.png)

**To Reproduce**
1. Create a Data Axis within a Glyph
2. Add a Number column to the data Axis
3. Change the Data Expression to be Quantile
4. See Parse Error: undefined Function Qantile

**Expected behavior**
I should be able to use this function in the Custom Visual

**Additional context**
How long does it take to move code from GitHub Repo into the custom visual for Power BI Desktop?

**Comment by dm-p** [comment]
I'm curious about this too - looks like we've only had one release of the custom visual since announcement (1.0.3).

**Comment by zBritva** [comment]
@dm-p yes, the first (it is also the last for now) version was published in mid of April. Please wait a next version.

**Comment by zBritva** [comment]
@dm-p @MikeCarlo the visual version 1.0.5. was published. This version includes the quantile function

**Comment by dm-p** [comment]
Thanks for the heads-up, @zBritva! Will there be a list of changes published anywhere? There's some stuff I've noticed which is quite obvious, but I'm wondering what other goodies might be there that I'm missing... :)

**Comment by bongshin** [comment]
@dmp You can find the list of updates and bugfixes (for Version 1.0.5) from the Power BI July 2021 Feature Summary blog post, https://powerbi.microsoft.com/en-us/blog/power-bi-july-2021-feature-summary/#post-16530-_Toc77174519.
