### ISSUE TITLE
Half Donut Chart Plot Segment Resize Issue

### ISSUE THREAD

**Issue by PBI-David** [microsoft/charticulator#596]
**Describe the bug**
I'm trying to create a half donut chart but the plot segment uses the entire diameter of the chart when resizing which means half the canvas is just blank space which cannot be removed. 

**To Reproduce**
1. Create a chart using a polar scaffold.
2. Set the polar coordinates from -90 to 90 so the chart takes up half the plot segment
3. Resize the plot segment and you will see the white space is retained

**Expected behavior**
Allow the plot segment to resize to the visible elements so that no white space is present

**Screenshots**
1.![Before resize](https://i.imgur.com/gCtR44A.png) 
2 ![After resize](https://i.imgur.com/FEwnB2w.pngl)

**Diagnostic information**
N/A

**Additional context**
N/A

**Comment by bongshin** [comment]
This issue is addressed in the latest deployment (on October 1, 2021).

![image](https://user-images.githubusercontent.com/9288805/135666986-4ecc1c63-7353-4fce-90c0-6e98f1ae35c9.png)

**Comment by PBI-David** [comment]
Amazing - thank you!
