### ISSUE TITLE
Rounded Bar Charts

### ISSUE THREAD

**Issue by PBI-David** [microsoft/charticulator#597]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to create a rounded bar chart or column chart but the available marks do not permit this

**Describe the solution you'd like**
A new mark with rounded corners 

**Describe alternatives you've considered**
N/A this is merely stylistic and would allow me to recreate some nice charts from Tableau

**Additional context**
![Example](https://1.bp.blogspot.com/gXomx8K_lWZugj0kL8U4VD409C_1YohfJAj_0ecS0el83PsKUtyu2qbEd-PXNK0R2ztiJc3jqd08IfvVSvBG1f1bTcdpzPfBMO0TdCFHd-BgLxMvPZC2CQ9A2za3-dWY7DOec5Y5Whg=w2400)

**Comment by MarkHaggett** [comment]
Have you watched [Charticulator Visual IS HERE!!! - Season 1 Episode 11 - Comet Chart](https://www.youtube.com/watch?v=kfwRJKUwdHE )? Whilst building a Comet Chart @dm-p does something like this.

**Comment by PBI-David** [comment]
Thanks. That's a very clever way of getting the desired result (with limits) but very hacky and convoluted. Native support for rounded corners would be fantastic and really open up design possibilities.

**Comment by dm-p** [comment]
Exposing rx and ry attributes on the rectangle mark could achieve this, preuming the team are open the the idea.

**Comment by ruthpozuelo** [comment]
I got this by accident...a bit hacky too, but depending on your data shape it might work?
![image](https://user-images.githubusercontent.com/19476550/124438578-a9d42a00-dd78-11eb-8a98-16231442d6a6.png)

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.1.1).

![image](https://user-images.githubusercontent.com/9288805/135782771-97328d9b-8e0d-4e90-974c-21dc780d8b39.png)

**Comment by PBI-David** [comment]
Thank you!
