### ISSUE TITLE
PBI Charticulator Visual Cross Highlighting Breaks With Unrelated Measure

### ISSUE THREAD

**Issue by PBI-David** [microsoft/charticulator#599]
**Describe the bug**
I have created a simple waffle chart in PBI Desktop. Everything works perfectly but I also want to add a text value via a measure to show some additional datapoints. When I add this second measure to the field well, the cross highlighting breaks. When I remove the measure, it resumes working again.

**To Reproduce**
File attached for reference. 
1.Verify cross-highlighting works as expected. 
2. Add the FruitPercent measure 
3. Verify cross-highlighting no longer works
4. Remove the measure
5. Verify that cross highlighting works again

**Expected behavior**
Adding an unused and unrelated measure should not break cross highlighting

**Screenshots**
![Image of Yaktocat](https://i.imgur.com/C85Cee8.gif)

**Diagnostic information**

**Additional context**
N/A
[Waffle Upload.zip](https://github.com/microsoft/charticulator/files/6759770/Waffle.Upload.zip)

**Comment by zBritva** [comment]
@PBI-David  The Charticulator doesn't support partial rendering (it can't map partially highlighted values into some property)

In your sample when you select Category `Bananas` the visual gets:

|  Category | Value  | Highlight  |
|---|---|---|
| Apples  | 100  |  null |
| Bananas  | 100 |  **100** |   
| Oranges| 100 | null |
|  Pears | 100 |  null |

**The visual highlights the category with values (null values get some opacity)**

With additional unused column the visual gest:

|  Category | Value  | Highlight  |
|---|---|---|
| Apples  | 100  |  21 |
| Bananas  | 100 |  21 |
| Oranges| 100 | 21 |
|  Pears | 100 |  21 |

There are all categories get values and all categories are highlighted.

Charticulator doesn't have mechanism to map highlighting values to attributes of marks (you can't say: "map 21 to opacity of symbol")

**Comment by PBI-David** [comment]
Hi @zBritva  - thanks for looking into this for me. Have I misunderstood your response as my issue is that Charticulator stops working when a completely unrelated measure is added to the field well in PBI Desktop. i.e. the visual works perfectly until I add the additional measure and even though the newly added measure is unused, it still breaks the previously working functionality.

**Comment by PBI-David** [comment]
Hi @zBritva - thanks for looking into this for me. Have I understood this correctly - even though the newly added measure is  unused, the data is _still_ flowing through to Charticulator? I would have thought that only mapped fields would be considered in the evaluation of what data to show in the chart and all other fields in the field well could be ignored?

**Comment by zBritva** [comment]
No, unused columns can change level of details. For example, with two columns you have 4 rows. with three columns you have 8 rows.
