### ISSUE TITLE
Add Segoe UI Bold, Segoe SemiBold, Segoe Light into fonts list

### ISSUE THREAD

**Issue by steve257** [microsoft/charticulator#606]
Can Segoe UI Bold, Segoe SemiBold, Segoe Light be added into fonts list.
As these are all already in Power BI and regularly used by lots of people.

**Comment by PBI-David** [comment]
On the subject of fonts, font sizes also need to be normalised. If you use a Tahoma size 10 in PBI and a Tahoma size 10 in Charticulator, they actually render at different sizes when viewed next to one another.

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.1.0).
