### ISSUE TITLE
Bar Chart?

### ISSUE THREAD

**Issue by QuSimone** [microsoft/charticulator#609]
Hello,

I am trying to create a simple bar chart, but running into an error when I do so. It seems the bars aren't sticking where I would expect them to. Here's a video of the issue:

https://user-images.githubusercontent.com/72839029/126201396-18ac25df-5cce-4268-9c84-1aae9462888d.mp4

The data in this Table is very simple:
![image](https://user-images.githubusercontent.com/72839029/126201689-10bc1a01-d9e3-45da-a6a3-886e3a7b52dd.png)

**Comment by zBritva** [comment]
Hello, I don't see the problem. When you drop numerical value to Y axis you bind the value to the vertical positions of glyphs(rects)
See https://charticulator.com/docs/user-interaction.html#layout-composition
I suspect you want to add the legend .

![image](https://user-images.githubusercontent.com/10897951/126202131-bfe9f5bd-4ebe-43e5-a1a2-360d25b71e56.png)

**Comment by QuSimone** [comment]
Yes, adding the legend is exactly what I'm trying to do. Apologies, I'm still getting used to this visual! Thanks! 

Consider this closed.
