### ISSUE TITLE
Option to Display X-axis Labels Vertically (ie., 90 degrees)

### ISSUE THREAD

**Issue by steve257** [microsoft/charticulator#620]
**Is your feature request related to a problem? Please describe.**
The labels on the x axis rotate to 45 degrees when there is NOT enough room to display them horizontally in Power BI.

**Describe the solution you'd like**
I would like the OPTION to display x axis labels vertically (ie., 90 degrees) instead of the forced 45 degree angle being imposed.

**Additional context**

![Snap1](https://user-images.githubusercontent.com/58976533/127194618-d94bf9a6-d5f6-46fc-b681-5b9f44957eb5.jpg)
Horizontal

![Snap2](https://user-images.githubusercontent.com/58976533/127194624-b20cfd74-f319-43d6-974a-5fc5c15bce93.jpg)
Forced 45 degrees

![Snap4](https://user-images.githubusercontent.com/58976533/127201327-e25f78b2-f8ba-4e4b-b03f-f02caea0a8ff.jpg)
Vertical

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.1.0).
