### ISSUE TITLE
Export to PNG, JPG or SVG not working

### ISSUE THREAD

**Issue by bitc-mattww** [microsoft/charticulator#669]
When exporting a chart, the export to PNG, JPG or SVG buttons do not work. Nothing happens when you click either of these buttons, no files are saved to downloads folders. Tried on both Edge 92.0.902.73 and Chrome 92.0.4515.131, tried adding Charticulator to allowed sites for popupts/redirects

**Comment by zBritva** [comment]
The fix was deployed. Thanks for reporting!
