### ISSUE TITLE
Visibility options for numerical values

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#670]
**Is your feature request related to a problem? Please describe.**
I would like to have more options on the visibility options for numerical values:
![image](https://user-images.githubusercontent.com/19476550/129726096-ab9bc006-e10c-42c5-8711-7c93c2528691.png)

**Describe the solution you'd like**
It would be great to get options like "isnotblank", "isblank", "equal to" "not equal to". 
I know I can create a measure that does that, and apply it, but it would be great to have it as an option without creating an extra measure.

**Comment by zBritva** [comment]
I think you can achieve it by DAX and it will be more powerful than simple expression in the visual.

**Comment by ruthpozuelo** [comment]
Hi @zBritva , you can, I mentioned that on the request, but for non-dax experts, it would be nice to have it as an option on the UI and in some cases, it will eliminate the need for adding additional measures which is always a good thing imo.

This is only a nice to have to make the tool more accessible.

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.1.2).
