### ISSUE TITLE
Drop elements in the glyph where I point rather than in the center

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#674]
**Is your feature request related to a problem? Please describe.**
When dropping text, marks, etc on the glyph area, they automatically are placed at the center and the glyph zooms out.

Depending on the type of chart being built, it can be a bit cumbersome to then place it where I intended from the beginning and zooming is not always a straight forward thing.
![drop elements](https://user-images.githubusercontent.com/19476550/129728497-aa8f8133-57c3-4182-8e21-381bb43ea5e0.gif)

**Describe the solution you'd like**
It would be great if elements would drop in the are you point when dropping so we dont have to zoom in and out all the time.

**Comment by zBritva** [comment]
Use clicks for that:

![mark_editor](https://user-images.githubusercontent.com/10897951/129763446-cc55cf9f-4673-4e8d-b7ca-bddf43603f56.gif)

You have to bind objects to guides. You can't drop them anywhere where you want.

**Comment by ruthpozuelo** [comment]
It works! and I can actually put objects anywhere! cooool :) Thanks!
