### ISSUE TITLE
Rectangular zoom in functionality for  the glyph

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#675]
**Is your feature request related to a problem? Please describe.**
Zooming in the glyph is a cumbersome thing and even though there is a + and - buttons, when you have to zoom and pan, it can take quite some time depending on the chart.

It would be great if we could have a rectangular zoom, meaning you draw a rectangle on the area you want to zoom in and it does it in one go.

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.1.2).
