### ISSUE TITLE
Blanks in the data breaks the charticulator visual

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#678]
**Describe the bug**
When I pick filters where there are no values in the table, charticulator shows me the edit mode rather than a blank chart.
Example:

![blanks break the visual](https://user-images.githubusercontent.com/19476550/129736742-5ac4852a-8766-49f2-83ee-922b476f9577.gif)

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.1.0).
