### ISSUE TITLE
Sort by a column 

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#704]
**Is your feature request related to a problem? Please describe.**
I would like to be able to sort plot segments (or any element) by another column rather than the values the element has.

**Describe the solution you'd like**
For example, In this case, I would like to be able to sort by sales for each country, rather than alphabetically.
![image](https://user-images.githubusercontent.com/19476550/131099719-0a481db4-0ff0-4e10-acc6-ee7582c243b8.png)

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.2.2).

![image](https://user-images.githubusercontent.com/9288805/147358010-525821be-c693-4728-b109-fdb3e1938e39.png)

**Comment by Amrselim-89** [comment]
i still have this issue, Any solution?!

**Comment by zBritva** [comment]
@Amrselim-89 what kind of issue with "Order by"?

![image](https://user-images.githubusercontent.com/10897951/202794948-3d7cc60b-fcad-44c1-b85b-ddf16734b087.png)

**Comment by Amrselim-89** [comment]
@zBritva Thank you so much for helping me, please review this video, it shows no matter I sort my plot segment by another colmn, it just does not follow this sort, any solution sir?!

https://user-images.githubusercontent.com/118567825/202797390-c1550e85-770c-4445-b9f2-0fb2e46effc5.mp4

**Comment by zBritva** [comment]
> @zBritva Thank you so much for helping me, please review this video, it shows no matter I sort my plot segment by another colmn, it just does not follow this sort, any solution sir?!
> 
> https://user-images.githubusercontent.com/118567825/202797390-c1550e85-770c-4445-b9f2-0fb2e46effc5.mp4
> 
> 

Thanks. I will investigate it. Will ping you soon

**Comment by Amrselim-89** [comment]
@zBritva  Hello Sir, Any solution approaches?!

**Comment by zBritva** [comment]
I tested on my side. And don't see issue with sorting. But the visual doesn't save column user for sorting, and I expect it can break sorting when new data is applied for the visual.

Unfortunately, there is not a workaround to avoid this bug.
