### ISSUE TITLE
Can scroll on number dropdown in Power BI

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#707]
**Describe the bug**
When I try to pick sum on the number dropdown. It is hidden and I can not scroll to get it. 
I am changing it manually for now:
![image](https://user-images.githubusercontent.com/19476550/131247464-56655542-73b9-4bb9-a3f4-a034a1c68588.png)

**Comment by zBritva** [comment]
The next version contains the fix:

![image](https://user-images.githubusercontent.com/10897951/131341003-6e6f86a6-b0bb-419a-a45b-c7caa6e2ce3e.png)

**Comment by ruthpozuelo** [comment]
Looking nice! 👏
