### ISSUE TITLE
Change precision on the y axis

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#710]
**Is your feature request related to a problem? Please describe.**
I would like to change the granularity for the Y-Axis, so it doesnt display the .5 values (the data has only integers), but even reading the d3 docs I cant figure it out. 
I dont know if it is because it is not possible or I am just simply doing it wrong?
![image](https://user-images.githubusercontent.com/19476550/131360000-e8e85304-a2b1-47c6-982d-f8371bddae00.png)

I tried changing the tick format to whole numbers, but still no luck:
![image](https://user-images.githubusercontent.com/19476550/131361580-55d80c20-0497-456d-9fd4-c4ad68908cc9.png)

If it is not possible, I would love to have it as feature to be able to specify the precision:
https://observablehq.com/@d3/axis-ticks

**Comment by zBritva** [comment]
You need to use "Tick Data" field to set custom ticks. But in current version of the visual it has issue, on saving it disappears

**Comment by ruthpozuelo** [comment]
ahh, makes sense! I tried the ticked data too, but nothing happened, so I thought I was using it wrong. Got it, will wait until it gets fixed.

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.4.1).
