### ISSUE TITLE
Guides on Data axis 

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#719]
**Is your feature request related to a problem? Please describe.**
I would like to have the possibility to add guides on data axis, so I can create a grid like this one:
![image](https://user-images.githubusercontent.com/19476550/131527146-9ca63052-462d-4801-943f-b92737719af6.png)
I can not find that setting on the data axis menu and as I have only data bind to the Y-axis on plot segment, I cant add the vertical guides:
![image](https://user-images.githubusercontent.com/19476550/131526625-05d2eb45-d1ca-41a0-8503-013db4e4204b.png)

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.1.0).
