### ISSUE TITLE
Adding precision to lengends when used as Y-Axis

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#737]
**Is your feature request related to a problem? Please describe.**
When we have to add a legend as Y-axis, we need to be able to format the Y-axis the same way with the "normal" Y-axis, but I dont see the options there.

![image](https://user-images.githubusercontent.com/19476550/132196934-789febdb-c9ae-4d31-9dc9-73f068d349d0.png)

**Describe the solution you'd like**
Instead of 200,000, I want to be able to format it as 200k.

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.1.2).
