### ISSUE TITLE
The X axis is not in chronological order, only in alphabetical order.

### ISSUE THREAD

**Issue by AmaralCamila** [microsoft/charticulator#754]
When I try to create a line chart, I insert a Name of the coming month column of Dim_Data, and the Chartculator sorts alphabetically, not chronologically.

![2  Chartculator](https://user-images.githubusercontent.com/90918857/133806352-b7a930b1-17bc-4e8a-9669-39ee78c96921.PNG)

I arrange the texts by individually dragging each one to the correct positions and the problem is fixed.

![1  ChartCulator](https://user-images.githubusercontent.com/90918857/133806120-9ac93f13-70a6-4026-b9ab-eb4db54cab78.PNG)

Although,
When I click to save the project, the text goes back to alphabetical order again.

You could solve this BUG, ​​because before this functionality worked normally in Brazil, but with an update, it stopped working.

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.1.2).
