### ISSUE TITLE
The Y axis starts with the value 0

### ISSUE THREAD

**Issue by AmaralCamila** [microsoft/charticulator#756]
Hello,

I created a line chart on the Chartculator website, but when I import the pbiz into Power Bi, unfortunately the Y-axis value doesn't start at Zero, and on the options roller doesn't have the option to input the zero value manually.

![Chartculator_04](https://user-images.githubusercontent.com/90918857/134101978-72aa6547-0c22-4c9f-81d6-60b25cdac2f9.PNG)

Hello,

I created a line chart on the Chartculator website, but when I import the pbiz into Power Bi, unfortunately the Y-axis value doesn't start at Zero, and on the options roller doesn't have the option to input the zero value manually.

![Chartculator_01](https://user-images.githubusercontent.com/90918857/134102238-900449bd-594e-4ce5-9283-b64171fe1c1c.PNG)

![Chartculator_02](https://user-images.githubusercontent.com/90918857/134102252-984dd478-59ad-4f72-9113-13e5ffcf3a22.PNG)

![Chartculator_03](https://user-images.githubusercontent.com/90918857/134102297-48256ed7-8f1d-473e-ab25-04dd2367bbcc.PNG)

**The solution to this problem could be to enable the Value "0 zero" to be entered manually, like Power Bi's native Line chart.**

![Chartculator_Solução](https://user-images.githubusercontent.com/90918857/134102462-b6f5ecf5-a5b6-499a-99fe-c3f589453cfa.PNG)

**Comment by zBritva** [comment]
@AmaralCamila try to use modern version of the visual:

https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA200002793?tab=Overview

You can find video tutorials from community, for example:
https://www.youtube.com/watch?v=afGc6-wFyy0&list=PLn1m_aBmgsbH31NHXuT9ArgY5ZefuKESo

The extension wasn't update in the last time and doesn't support new features.

**Comment by AmaralCamila** [comment]
> @AmaralCamila tenta usar uma versão moderna do visual:
> 
> https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA200002793?tab=Overview
> 
> Você pode encontrar tutoriais em vídeo da comunidade, por exemplo: https://www.youtube.com/watch?v=afGc6-wFyy0&list=PLn1m_aBmgsbH31NHXuT9ArgY5ZefuKESo
> 
> A extensão não foi atualizada na última vez e não oferece suporte a novos recursos.
