### ISSUE TITLE
Y Axis Value does not start at Zero

### ISSUE THREAD

**Issue by AmaralCamila** [microsoft/charticulator#768]
**Is your feature request related to a problem? Please describe.**
X axis value does not start at Zero

**Describe the solution you'd like**
I would like the Y-Axis value to start with a Zero value

![Eixo Y chart](https://user-images.githubusercontent.com/90918857/135909941-aefdf305-4298-46aa-9a0d-fb36f2feef7b.JPG)

**Describe alternatives you've considered**
Segue os procedimentos que adotei para resolver o problema, porém sem sucesso. 

![0  Gif](https://user-images.githubusercontent.com/90918857/135910174-cd5fcf44-df54-4557-b55a-adc99f9c2b74.gif)

**Additional context**
Are there any solutions to treat this problem?
Because the analyzes are greatly impaired with the value of the Y axis becoming automatic. Before there was an option of the value of the Y axis starting at zero, could it return with this option?

**Comment by MaryNost** [comment]
I'm facing this same problem, is there an update forecast for this bug?

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.1.2).
