### ISSUE TITLE
Enable tooltip from other report pages

### ISSUE THREAD

**Issue by AmaralCamila** [microsoft/charticulator#770]
**Is your feature request related to a problem? Please describe.**

I wish it was possible to enable the tooltip to use graphics from other pages, as in the example below

![Tooltip Novo](https://user-images.githubusercontent.com/90918857/135914034-f73e885e-b4be-45fd-bc66-63e6df4a806b.jpg)

**Describe the solution you'd like**

![Recurso para Tooltip](https://user-images.githubusercontent.com/90918857/135914952-ccc59aee-0971-45f5-90aa-9c02c8592809.jpg)

**Additional context**
This feature will undoubtedly make more users use the chartulator

**Comment by zBritva** [comment]
@MrRamka You need to [add "tooltips" property](https://docs.microsoft.com/en-us/power-bi/developer/visuals/add-tooltips#add-tooltips-support-to-the-report-page) in capabilities.json to enable report page tooltips

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.1.2).
