### ISSUE TITLE
 resize elements

### ISSUE THREAD

**Issue by AmaralCamila** [microsoft/charticulator#779]
**Is your feature request related to a problem? Please describe.**

As shown in the image below, I want the bar to occupy only 50% of the container vertically.

I make all the necessary settings and when I click save the formatting is lost.

![0  Redimensionando](https://user-images.githubusercontent.com/90918857/136804363-3c833894-d798-449c-8f52-9f2b0e28b33e.gif)

**Describe the solution you'd like**

I would like the charticulator to recognize the settings made, so that we could choose the size of the elements inside the container, either vertically or horizontally.

![Charticulator corrigido](https://user-images.githubusercontent.com/90918857/136805473-728d5723-8aa9-48d2-8205-688c8edb149c.jpg)

**Describe alternatives you've considered**

I went to the Guides tab and inserted a Y Guide (however, it seems that by default it comes with 2 lines aligned in the center, it would be interesting to be the same as before, where these two lines are prepared at the beginning and end of the container, to that we could choose how many guides we would like and thus reposition the elements)

![0  Inserindo Guias](https://user-images.githubusercontent.com/90918857/136805418-6a5441a7-441d-478d-9710-6a6871ece974.gif)

**Comment by AmaralCamila** [comment]
@zBritva Thank you very much for the quick return. Actually doing that worked 😍😍😍

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.1.2). Charticulator properly anchors the corners the rectangle when you drag its side.
