### ISSUE TITLE
Recognize text in data label

### ISSUE THREAD

**Issue by AmaralCamila** [microsoft/charticulator#780]
**Is your feature request related to a problem? Please describe.**

I have the numerical measure (Sales), in which the value is too large to be displayed on the axis, as shown in the image below

![Number comprido](https://user-images.githubusercontent.com/90918857/136962461-58101e9f-cb4c-4a76-8b99-203386bb243f.JPG)

**Describe the solution you'd like**

I would like you to have the option that we could shorten the amount.

![Number comprido Solution](https://user-images.githubusercontent.com/90918857/136963144-4c0b3a66-7e26-4387-99af-af9fe78d85c6.JPG)

**Describe alternatives you've considered**

The solution I tried was to create a measure, which returns a text with the abbreviated value, and insert it in the chart, but the charticulator does not recognize the measure as a text.

Below the measure that was created

![number comprido_2](https://user-images.githubusercontent.com/90918857/136963768-f0e0c10e-e160-4c1a-aa2e-95f41cd99257.JPG)

But this error occurs:

![Erro](https://user-images.githubusercontent.com/90918857/136964025-65ad90c0-e71c-4164-a188-8fb11abc80c1.JPG)

**Comment by bongshin** [comment]
@AmaralCamila Charticulator's format specifier follows d3’s syntax: https://github.com/d3/d3-format#format. Please try "\\$${avg(Sales)}{.3s}" as shown below.

![image](https://user-images.githubusercontent.com/9288805/137063675-9ee3a8bb-23a4-45ba-a289-7cd6ef233a6d.png)
