### ISSUE TITLE
Possibility to hide the top guide on Y axis

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#801]
**Is your feature request related to a problem? Please describe.**
When adding guides to an axis, the guides are added to the ticks and also to the last tick of the axis, which is not necessary in most cases. I would like to be able to hide it:
Hide the top one:
![image](https://user-images.githubusercontent.com/19476550/138353883-b3539893-1b9a-481c-a4b2-4d6eea424ab0.png)

![image](https://user-images.githubusercontent.com/19476550/138353855-702a3234-4609-437a-a339-28b561eb66f6.png)

**Comment by bongshin** [comment]
This issue is addressed in the recent release (Version 1.2.0).
