### ISSUE TITLE
Rotate the triangle symbol

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#805]
**Is your feature request related to a problem? Please describe.**
I would like to be able to rotate the triangle symbol so I can use it as an arrow. It it is not possible it would be useful to have a symbol for the most common directions (up-down-left-right)
![image](https://user-images.githubusercontent.com/19476550/138646943-45c4474c-357b-4f4d-8a57-0bc493d58773.png)
I can find the rotate attribute:
![image](https://user-images.githubusercontent.com/19476550/138647009-df28db4b-0a31-42dc-b400-93bfa77e3fd7.png)

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.1.2).
