### ISSUE TITLE
Visual won't save in Power BI

### ISSUE THREAD

**Issue by MareBou** [microsoft/charticulator#821]
Changes won't save when editing a Power BI charticulator visual. 
Save button does not save, when returning to report prompt will ask if we want to save change, again save button does not work and only option to get rid of prompt is to select "don't save". Visual is not updated with changes.

**Comment by laurajludwig** [comment]
I'm experiencing the same issue.

**Comment by bongshin** [comment]
@MareBou and @laurajludwig With this limited information it is not possible to figure out why you’re experiencing this issue. Would it be possible for you to provide additional information, such as dataset (w/ data types), the chart design (e.g., axis mapping, the use of data axis), screenshots, etc. so that we could try to reproduce the issue?

**Comment by MareBou** [comment]
Hello,
I was able to reproduce the issue with a fairly simple mock data set. Bear with me as I describe the steps that lead to the save button not working, hoping that you will be able to reproduce the issue, but the same thing happened to different data sets and different visuals, both using Power BI desktop or Power BI service to edit the report. 

TL/DR : Initially it works well and as I save and go back to edit, it starts not working right. In this particular case, it started acting funny starting at step 45 and stopped working at step 57.

Attached is an Excel file with the mock data set, and screencapture of the pbix file (I'm not able to upload the pbix).

**Steps taken in power BI desktop :** 

1. - Enter data in new **Data** table : **Country** (Format Text), **Material** (Format Text), **Score** (Format General)
2. - Create two measures :
_AverageScoreForRanking_ = Average (Data[Score])
_Rank_ = if(ISBLANK([AverageScoreForRanking]),BLANK(),RANKX(ALL(Data[Material]),[AverageScoreForRanking]))
3. Create Matrix visual to confirm measures are good : Rows = Country, Material. Values = AverageScoreForRanking, Rank
4. Add Charticulator visual 
5. Add the following fields in "Data" for the visual : **Country**, **Material**, **Rank**, **AverageScoreForRanking**
6. Edit Charticulator visual
7. Create new Chart
8. PlotSegment1 : Assign Country to X axis
9. Change Rank data to Categorical
10. PlotSegment1 : Assign Rank to Y Axis
11. PlotSegment : Position of X axis set to Opposite
12. PlotSegment1 : Sublayout = Grid
13. Glyph : Add a rectangle mark (_Shape 1_)
14. Shape 1 : Fill color is linked to **Material**
15. Save chart
16. Back to report
17. Edit chart
18. Plot Segment 1 : Sort Y axis by rank number
19. Glyph : Add text (_Text1_) 
20. Text1 : Anchor to X left, Y middle (left of the rectangle mark)
21. Text1 : Link text to **AverageScoreForRanking**
22. Save chart
23. Back to report
24. Add tooltip fields to charticulator visual : **Material**, **Rank**, **AverageScoreForRanking**
25. Save pbix file
26. Edit chart
27. Glyph : Add symbol (_Symbol1_)
28. Symbol1 : Anchor to middle of Shape1
29. Symbol1 : Shape linked to **Material**
30. Symbol1 : Fill color set to black
31. Save chart
32. Back to report
33. Edit chart
34. Add GuideY (2 count) to upper half of chart area
35. Anchor upper limit of PlotSegment1 to new guide to make place for a new plot segment above
36. Add a new glyph (_Glyph1_)
37. Add a new 2D plot segment for that glyph (_PlotSegment2_), above PlotSegment1
38. PlotSegment2 : Assign Country to X axis
39. Glyph1 : Add data axis linked to **AverageScoreForRanking** (_DataAxis1_)
40. Glyph1 : Add Rectangle mark linked to DataAxis1 / AverageScoreForRanking anchor (_Shape2_)
41. PlotSegment2 : Group by Country
42. PlotSegment2 : X axis position to "opposite"
43. DataAxis1 : Set min to 40, auto max
44. Save chart
45. Back to report --------!!!!! Message box asks if I want to save changes, asks to choose between "save" or "don't save". Save button will not click, I click on don't save but steps 34 to 43 seem to have been updated successfully in visual
46. Edit chart
47. Shape1 : Add Stroke (black)
48. Shape1 : Set Round X to 3 and Round Y to 3
49. PlotSegment1 : Set Gap X to 1% and Gap Y to 1%
50. PlotSegment2 : Set Gap X to 1%
51. Shape2 : Change Fill to Green
52. Shape2 : Add Stroke (black)
53. Glyph1 : Add text to Shape2 (_Text2_)
54. Text2 : Anchor to X middle, Y bottom 
55. Text2 : Link text to **AverageScoreForRanking** 
56. Hide DataAxis1
57. Save Chart --------!!!!!! Button does not respond
58. Back to report --------!!!!! Message box asks if I want to save changes, asks to choose between "save" or "don't save". Save button will not click, I click on don't save and changes from steps 47 to 56 are lost
59. Save pbix file
60. Edit chart
61. Shape2 : Change fill to green
62. Save Chart --------!!!!!! Button does not respond
63. Back to report --------!!!!! Message box asks if I want to save changes, asks to choose between "save" or "don't save". Save button will not click, I click on don't save and changes are lost

[MOCK_DATA (2).xlsx](https://github.com/microsoft/charticulator/files/7499379/MOCK_DATA.2.xlsx)
![CapturePBIX](https://user-images.githubusercontent.com/93656784/140800656-d98d3ddc-8d49-4e39-ab98-432f4015c537.PNG)

**Comment by zBritva** [comment]
@MareBou try to remove columns from tooltips bucked before editing a chart. I hope it should help

**Comment by zBritva** [comment]
@MrRamka there is output:

![image](https://user-images.githubusercontent.com/10897951/140810003-72c95c39-8395-4e66-8770-a1e10b1d8450.png)

![image](https://user-images.githubusercontent.com/10897951/140810084-a85b71fd-54e7-448b-aa5f-4d36f806b5fd.png)

The visual handles tooltips table as links table and try to map table into template where is no links table.

See 'initializeTemplate' method in reducer.

**Comment by MareBou** [comment]
Thanks @zBritva , removing the columns in Tooltip did work. The save button works now.

**Comment by laurajludwig** [comment]
Removing tooltips also allowed me to save updates to my visual, and re-add Tooltips after saving.

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.2.1).
