### ISSUE TITLE
Text values do not update after source content change

### ISSUE THREAD

**Issue by lalalere** [microsoft/charticulator#829]
At the beginning, I want to display data label but only those I want, like this 👍 
![image](https://user-images.githubusercontent.com/71875148/140638039-f6e46155-02d4-4bf6-b526-7e76aa31ad3c.png)

Then I see that I don't want the "(1)" after Hybrid and I prefer "Electrique" than "Electricité".
![image](https://user-images.githubusercontent.com/71875148/140638096-d21c2b85-5311-4f8d-992d-3996d3e4ab21.png)

So I changed the source content.
This is well taken into account  here 👍 
![image](https://user-images.githubusercontent.com/71875148/140638114-e7668917-5a38-4cbd-aa4b-682eaa054235.png)

But after several refreshes, updates, close and reopening, I still get this 👍 
![image](https://user-images.githubusercontent.com/71875148/140638160-6467c35b-b1b1-439b-a9fc-925f87ebdfb2.png)

Thanks

**Comment by ruthpozuelo** [comment]
Which version of charticulator do you have?
They have recently added this;
![image](https://user-images.githubusercontent.com/19476550/140649815-5dc1c989-0eab-4f06-b85c-21c11a2bf3a1.png)

**Comment by lalalere** [comment]
I have this screen too. This was'nt the point. 
Besides, this option does not work very well. Did you try it deeply?

**Comment by ruthpozuelo** [comment]
It is working for me. It is something else you are facing, then I am out of ideas!

**Comment by ruthpozuelo** [comment]
I just got the same issue as you! 
The auto update does not apply for Visibility values and we definately need that too.
In the example below, the color code changed from Negative to decrease and it doesnt reflect on the visibility items.
![image](https://user-images.githubusercontent.com/19476550/140747352-f06d6634-440d-4f05-b74a-c5dc3c3bec87.png)

**Comment by lalalere** [comment]
Thanks Ruth! I was crazy about all of this!

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.2.1).
