### ISSUE TITLE
Text background color

### ISSUE THREAD

**Issue by lalalere** [microsoft/charticulator#831]
**Is your feature request related to a problem? Please describe.**
I do not manage displaying data label correctly depending on the data color.

**Describe the solution you'd like**
I would like to have a text background color as in all standard power bi visuals.

**Describe alternatives you've considered**
As a (bad) workaround, I have added another shape behind the text, but its size is related to the glyph and not to the text lenght.
![image](https://user-images.githubusercontent.com/71875148/140660708-cf382b77-9c52-4304-94a0-9521c506168d.png)

And the result is not perfect
![image](https://user-images.githubusercontent.com/71875148/140660766-49ec3fce-b78b-4bc8-b0a3-3922161a78cf.png)

thanks :)

**Comment by ruthpozuelo** [comment]
+1
Would like the same for the axis too:
![image](https://user-images.githubusercontent.com/19476550/142287048-a2d4fa84-22cf-4fa5-8264-cfedcf93b10c.png)

**Comment by lalalere** [comment]
oh yes!

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.2.2).

**Comment by lalalere** [comment]
Many thanks!!!
![image](https://user-images.githubusercontent.com/71875148/147385487-9b1e6ecb-69ca-4751-a260-ac4a2bd35c28.png)
