### ISSUE TITLE
Certification

### ISSUE THREAD

**Issue by PBI-David** [microsoft/charticulator#837]
Can anyone tell me when Charticulator will become certified? I would love to start using this at work (as I'm sure would many others) but until it is certified, I am unable to do so.

**Comment by ruthpozuelo** [comment]
+1

Vote here to integrate it in power bi:
https://ideas.powerbi.com/ideas/idea/?ideaid=6d7d6592-3aff-4b83-a4cf-806b593fc841

**Comment by PBI-David** [comment]
Thanks Ruth and already voted. It would be nice to get an ETA from the dev team for when certification is expected.

**Comment by ruthpozuelo** [comment]
The flow app got into the product without certification first, hopefully the same will happen with charticulator.
If you can, help get people to vote ;)

**Comment by PBI-David** [comment]
Bump. Is certification on the roadmap? Just an approximate indication would be good to know.

**Comment by ruthpozuelo** [comment]
I am sure it is. What they explained is that if they certify it too soon it will be too difficult to do updates, so they want to iron out all the bugs first and then certify it.
Don’t know if they have a target date though..
