### ISSUE TITLE
Links to close when a polar scaffold is used

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#844]
**Is your feature request related to a problem? Please describe.**
When creating a radar chart (for example), the links need to close on themselves to do it properly:
![image](https://user-images.githubusercontent.com/19476550/142287466-cdda9b88-1f70-4bf3-abfd-6ab44891846e.png)

It is possible to get it done with a links file, which is great, but they are a hassle to make.
Could it be possible to have a option on the links menu to close on itself when using polar axes?

![image](https://user-images.githubusercontent.com/19476550/142287549-aa5f9c98-b055-4833-a567-9a31693bb592.png)

Link to the pbix:
[radar chart (curbal).txt](https://github.com/microsoft/charticulator/files/7558510/radar.chart.curbal.txt)

**Comment by dm-p** [comment]
I'd probably suggest extending this request to allow an attribute to close them **if** we link by a categorical field - not that I'm a particularly huge fan of polar scaffolds, but a creator may want the option to continue a line as it can currently (e.g. if a temporal field is used)

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.2.2).
<img width="234" alt="image" src="https://user-images.githubusercontent.com/9288805/147357502-a58489a0-88d8-4816-94d1-4ad4aea0ef7e.png">
