### ISSUE TITLE
Charticulator does not load in Power BI

### ISSUE THREAD

**Issue by Seebaer1986** [microsoft/charticulator#846]
**Describe the bug**
When I try to create a new charticulator visual in a clean new Power BI file, it will not give me the option to start working, after I clicked the three ellipsis.

**To Reproduce**
1. Create a new charticulator visual in Power BI
2. drag a field into the data section of the visual
3. Click on '...'
4. Click on 'Edit'
5. See problem...

**Expected behavior**
Option to create a chart should be visible:
![image](https://user-images.githubusercontent.com/22417079/142457373-bf9e2422-bf82-4d82-91ba-b3f5e400774a.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/22417079/142457260-d2548925-0480-4947-a8f7-6de753045a2e.png)

**Comment by zBritva** [comment]
It seems you are using only measure with aggregation. Try to add categorical data column too.

**Comment by Seebaer1986** [comment]
Actually it does not matter what kind of data I put into the visual:
![image](https://user-images.githubusercontent.com/22417079/142486839-60ec3b84-3a47-43e8-8b4c-da8167842187.png)

And even if, the expected behavior should be that I see this:
![image](https://user-images.githubusercontent.com/22417079/142486926-e09ac482-60a3-427e-b1dc-a15dd4bb90b1.png)

The interface but the buttons greyed out. 

What I see is the step by step instructions how to get going...

**Comment by Seebaer1986** [comment]
No you are right, since the year was automatically summarizing the chart did nothing. My bad!
![image](https://user-images.githubusercontent.com/22417079/142487659-3026dc8e-d545-4fde-9aa1-e8f3540b88bb.png)

**Comment by zBritva** [comment]
@MrRamka parsing of filter values fails in reducer (UPDATE_FILTERS_SELECTION):

![image](https://user-images.githubusercontent.com/10897951/142492634-a8f179d2-b736-4998-bf5e-e9eccdd63cf7.png)

When dataview doesn't have categorical values:

![image](https://user-images.githubusercontent.com/10897951/142492746-00a851d4-d541-41b3-a1ca-322a47df1c92.png)

**Comment by zBritva** [comment]
@Seebaer1986 it's bug. Let's keep it open.

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.2.1).
