### ISSUE TITLE
change the highlight pattern

### ISSUE THREAD

**Issue by AmaralCamila** [microsoft/charticulator#856]
**Describe the bug**

The charticulator's highlight pattern when we perform a filter is white, but when we have a dark background it is not so pleasant for the end user.

as shown in the image below, the columns that were not selected are white

![Padrão](https://user-images.githubusercontent.com/90918857/143240443-d5b21f36-6d9a-4e65-81d7-48ed4043b2d0.JPG)

**Expected behavior**

I would like it to have the same behavior as native charts, where unselected columns remain the same color with transparency, shown in the image below.

![Gostaria](https://user-images.githubusercontent.com/90918857/143240917-59f37cc6-f128-4744-b75e-1e8715b47faa.JPG)

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.2.2).
