### ISSUE TITLE
export template is blocked

### ISSUE THREAD

**Issue by martinvegamercado** [microsoft/charticulator#869]
good morning. When wanting to export a template to be able to make the same graphic in other files, the chaticulator in power bi tells me that this option is blocked by the administrator. I didn't do it before. that could be happening?

**Comment by arnohoedelmans** [comment]
Hi i have the same issue!

**Comment by MikeCarlo** [comment]
I have the same issue. Says blocked by administrator?? 
Not a cool feature, can we get this resolved.

**Comment by MikeCarlo** [comment]
This has been resolved, This is a new Power BI Tenant setting that needs to be changed. 

here is the video that explains how to resolve the issue: 
https://youtu.be/SPV2EIWlyJs

**Comment by MikeCarlo** [comment]
> good morning. When wanting to export a template to be able to make the same graphic in other files, the Chaticulator in power bi tells me that this option is blocked by the administrator. I didn't do it before. that could be happening?

I think this issue is now resolved, and no longer an issue, might want to close this one out.

**Comment by bongshin** [comment]
The latest release (Version 1.2.3) includes the old capability (i.e., copy a template to the clipboard) as well.
<img width="147" alt="image" src="https://user-images.githubusercontent.com/9288805/149164896-a3e3060f-c430-400c-bedd-1e4e3891f4bf.png">
