### ISSUE TITLE
Charticulator in Power BI stuck on "Working"

### ISSUE THREAD

**Issue by issowi** [microsoft/charticulator#870]
Just found this tool and was attempting to make a Circular Barchart.  I added my 3 fields started creating my chart and when I added Month Name to the angular axis the chart shows "Working..." but never brings the data in. 
 
![image](https://user-images.githubusercontent.com/7000241/146040297-ff91ac58-e489-436f-bcd1-b041a9d24632.png)

**Comment by bongshin** [comment]
Please make sure that `Month Name` is added to the **Data** section in the Visualizations Pane in Power BI. The Links section is for the link-related data fields to create a chart with links between glyphs.

**Comment by issowi** [comment]
> 

Thank you so much!

**Comment by issowi** [comment]
Fixed
