### ISSUE TITLE
Data driven or dynamic range of data axis

### ISSUE THREAD

**Issue by lalalere** [microsoft/charticulator#875]
Hi,
When I create a data axis for my glyph, the minimum and maximum are automatically created which is good.
![image](https://user-images.githubusercontent.com/71875148/147266026-7c97eb54-50da-4509-98f1-615266d4fdcf.png)

And here is my visual 
![image](https://user-images.githubusercontent.com/71875148/147266132-f81e6c94-aa80-4b1e-80b7-8a706fca46cd.png)

Great.
But when I modify some data selection, I can obtain this result within the same chart : 

![image](https://user-images.githubusercontent.com/71875148/147266266-653a59ac-a46c-4f7b-82a1-4fead4feaeea.png)

because the range has not been modified accordingly.

**What I would like is the ability to put a measure inside the range, or that the range can dynamically adapt the data axis range** 
![image](https://user-images.githubusercontent.com/71875148/147266661-158627d0-9c65-4f54-92aa-7a7678a9fd1e.png)

to get this
![image](https://user-images.githubusercontent.com/71875148/147266588-652f6892-b66f-466d-a510-608fe1b2de6c.png)

Many thanks for your work,
Céline from adorem-conseil.fr

**Comment by MrRamka** [comment]
Hi. Would it be possible for you to provide additional information, such as dataset (w/ data types), the chart design (e.g., axis mapping, the use of data axis), etc. so that we could reproduce the issue? The pbix file (with fake data) would be the most helpful, if possible.

**Comment by lalalere** [comment]
I am trying to reproduce the issue with another dataset, but I can't because of th bug #880 
I just feel that I will not be able to reproduce it. This seems to work with another file... I don't understand why. I will check again. Thanks

**Comment by lalalere** [comment]
I am not able to reproduce the bug with another data set. You can close this bug.
