### ISSUE TITLE
Autoscale gradient fill

### ISSUE THREAD

**Issue by Minova2018** [microsoft/charticulator#876]
**Is your feature request related to a problem? Please describe.**

When I add a numeric field to a the fill property of a mark the marks get a gradient fill based on the highest and lowest values. Which is good. But when I save to Power BI and adjust a filter (e.g. a different month) the range doesn't get updated. Which actually defeats the purpose of the chart I have made.

**Describe the solution you'd like**
Allow for auto min / auto max on a legend

<img width="235" alt="Legend Range" src="https://user-images.githubusercontent.com/74718885/147280964-b4fb015e-d47a-480c-87d8-dfa4e8ad657f.png">

**Describe alternatives you've considered**
Increase the size of a mark instead of the color. Doesn't work in my scenario however.

**Comment by lalalere** [comment]
I think this issue is linked to mine : #875

**Comment by bongshin** [comment]
This issue is addressed in the latest release (Version 1.4.1).
