### ISSUE TITLE
order by field not respecting power bi order by column

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#890]
Hi ,
I am testing the order by column where i try to order an x axis by month name:
If i use the month column, the default order is alphabetical order. 
![image](https://user-images.githubusercontent.com/19476550/149667613-77e9bee5-8bfc-48ae-b1f1-a4f0b2f83966.png)
even though I have already specified in power bi that month name column should be ordered by month number.
![image](https://user-images.githubusercontent.com/19476550/149667661-e461c8fa-bb56-468c-b222-5957bcf89ebf.png)

The only way to make the order column work is to sort manually in charticulator. Is this behaviour expected?

**Comment by bongshin** [comment]
This change was made to address [the issue #704](https://github.com/microsoft/charticulator/issues/704). Charticulator automatically order the axis based on the data value when you assign a data column to the axis. You can use the order passed from Power BI by resetting the order (i.e., clicking on the Reset button). That said, we found issues with using this feature with a different column and we are working on them.

**Comment by ruthpozuelo** [comment]
Are you saying that if I order the month column in power bi charticulator will respect it? Because it didn’t do it for me?

**Comment by bongshin** [comment]
Yes, the "Reset" is supposed to respect to the original order in the data, which is determined by Power BI in this case (i.e., with the Charticulator visual): you can check it from the data table by clicking the “…” button from the Dataset Panel. Note that you can produce a semantically confusing outcome. For instance, in the example below, I did **reset** the order (with the `Month` assigned to the "Order by" field) while Power BI sort the data by the `Steps` column.

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/9288805/151039432-a6fe3f55-9e40-4d0c-8ef8-d25fcc30e75c.png">

**Comment by ruthpozuelo** [comment]
Interesting, I need to test that again, because it didn’t do it for me. I will test it again and close the issue if it is doing it , otherwise I will share my file.
Thanks for the explanation!

**Comment by ruthpozuelo** [comment]
I tested it again and i still can not get sorted properly, so I wonder if maybe we are talking about different sortings?
![image](https://user-images.githubusercontent.com/19476550/151055655-016ac795-b732-47f6-a6dc-ae97f1bd4fb4.png)

So the sorting I mean, is not the visual sorting but the column sorting. In the case below the column Month name is being sorted by column number and that is respected when sorting the visual ascending or descending.
![image](https://user-images.githubusercontent.com/19476550/151055726-a5a6033d-d3cc-40b8-b377-24ecea3409f8.png)

Attach my test file
[Northwind Power BI final report-2021.pbix.txt](https://github.com/microsoft/charticulator/files/7936978/Northwind.Power.BI.final.report-2021.pbix.txt)

**Comment by bongshin** [comment]
![sort-reset](https://user-images.githubusercontent.com/9288805/151217288-04144708-517e-4423-a0f5-db27fd89c52c.gif)

**Comment by lalalere** [comment]
@ruthpozuelo I always add an "order" colum in my base table to order fiels the way I want, even with month. I was fed up to struggle with the order tool ...

**Comment by ruthpozuelo** [comment]
I tried again and if I reset the order as @bongshin  suggests (I have to do it twice that was my issue), it sorts properly now, so I will close the issue.
For anyone having issues, you might need to reset more than one time. Resetting once and then trying to sort in power bi will not do it.

**Comment by lalalere** [comment]
👍
