### ISSUE TITLE
Legend display and color mapping to circle not working correctly in dumbbell template

### ISSUE THREAD

**Issue by yahsee** [microsoft/charticulator#895]
**Describe the bug**
Using the dumbbell chart template and sample data, legend not displaying correctly and mapping of color legend to Male circle symbol not working. This issue has been replicated in various ways, using the template and sample data, and using other data and following the dumbbell tutorial from scratch.

**To Reproduce**
1. Import dumbbell sample data (https://charticulator.com/data/g7_unemployment_gender_gap.csv) to new PBI project
2. Add variables to Charticular values visual (in same order as data table and ensure Don't Summarize selected for all)
3. Edit Charticulator, Import dumbbell template (https://charticulator.com/templates/dumbbell_chart.tmplt), check mapping and Save mapping.
Since the above steps resulted in only Women displaying legend and circle, I also duplicated the report page and tried the following additional steps, which did not fix problem:
4. Delete legend
5. Create new legend by selecting Men and Women columns
6. For symbol 1, drag legend to fill and select color corresponding to Women; for symbol 2, drag legend to fill and select color corresponding to Men (color for Men continues not to show, legend seems to display correctly in editor, but doesn't show color for Men on load)

**Expected behavior**
Legend should display both Men and Women, and circle symbol fill mapped to legend should display correctly

**Screenshots**
<img width="1423" alt="bug" src="https://user-images.githubusercontent.com/11956541/150027705-8bf1041a-b521-47dd-a1ae-426bf7215076.png">

**Diagnostic information**
If applicable, provide diagnostic information (you can get it by copying it to clipboard).

**Additional context**
pbix attached as a zip file

[dumbell_chart_bug.zip](https://github.com/microsoft/charticulator/files/7892713/dumbell_chart_bug.zip)

**Comment by bongshin** [comment]
This issue is addressed in version 1.3.0.
