### ISSUE TITLE
No ability to scroll within the larger application window

### ISSUE THREAD

**Issue by JustinGOSSES** [Microsoft/charticulator#9]
You can't scroll within the application, so if you're screen is smaller than the default size, you'll not see options like changing the style of marks in the attributes menu. 

This was experienced on a 2016 macbook pro 15 inch screen.

**Comment by bongshin** [comment]
We decided not to add a scrollbar to the main window. 

We instead allow you to customize the position, size, and docking status of the Glyph Editor, Layers Panel, and Attributes Panel.
