### ISSUE TITLE
Move glyphs to the front or back

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#913]
**Is your feature request related to a problem? Please describe.**
I have been trying to move glyphs from the front to the back, but I cant seem to be able to do it?
**Describe the solution you'd like**
I would like the "remain glyph" (black bar) to be on the front, so I would like to drag and drop it before the "leave glyph":
![image](https://user-images.githubusercontent.com/19476550/153294628-6cacaa87-f435-43f3-92de-644dd94f10f2.png)

I know i can move elements within a glyph, but I cant manage to move the glyphs around.

**Comment by dm-p** [comment]
Hey @ruthpozuelo - did you try moving the order of the plot segments the glyphs belong to rather than the glyphs? This is typically how I change layer order in these scenarios (but it's been a while).

**Comment by ruthpozuelo** [comment]
of course @dm-p !! I dont know what i was thinking!!
