### ISSUE TITLE
Sort nested charts 

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#951]
**Is your feature request related to a problem? Please describe.**
How do i sort nested charts? I have tried using power bi sorting, but i am unsure if it is possible?
I would like the highest value to be first chart.

![image](https://user-images.githubusercontent.com/19476550/156783857-40ffb477-65a4-4389-9ba6-3cd3c4e6333f.png)

**Comment by MrRamka** [comment]
If you have `Grid` Sub-layout type you, can use the `Orientation` and `Direction` properties.
![nested-order](https://user-images.githubusercontent.com/41204824/156786271-b4c101c8-b807-4c24-ab56-bed6e2504333.gif)

**Comment by ruthpozuelo** [comment]
I got it! I was able to sort it using the order column.
![image](https://user-images.githubusercontent.com/19476550/157001490-4cc7e502-3abf-432d-b40d-15ae32598ef4.png)
