### ISSUE TITLE
Fill with different colors on nested charts

### ISSUE THREAD

**Issue by ruthpozuelo** [microsoft/charticulator#958]
**Is your feature request related to a problem? Please describe.**
Hi, I am trying to reproduce this chart:
![image](https://user-images.githubusercontent.com/19476550/157715007-e36895fc-d0c6-4741-a96d-7821f208ab6a.png)
but when I try to get the circles with different colors, only the one active when building gets colored. Is there any way to specify the colors for the other nested charts?

![image](https://user-images.githubusercontent.com/19476550/157715208-d8f37d7a-b539-4c57-895c-bcc119a48d89.png)
here is what happens:
![image](https://user-images.githubusercontent.com/19476550/157715283-6fd6b01f-15e3-46f3-a100-7d057b2af526.png)

**Comment by zBritva** [comment]
It's related to https://github.com/microsoft/charticulator/issues/217 and https://github.com/microsoft/charticulator/issues/144

For now, you need to [use workaround](https://www.youtube.com/watch?v=cLiZpifYF4A) to resolve the issue

**Comment by ruthpozuelo** [comment]
Hi @zBritva , 
the workaround you where referring to was to add labels manually?
![image](https://user-images.githubusercontent.com/19476550/157733088-ea9a82f9-1b55-4bf0-8d68-f8eec6472c09.png)
Because I can add labels, but I can not change the names so it wont pick the colors up. Is this a bug ?

**Comment by zBritva** [comment]
Yes, you can. But at the end of the video author shows better way for that

**Comment by ruthpozuelo** [comment]
Fabulous!! 🎉🎉🎉

![image](https://user-images.githubusercontent.com/19476550/157745442-4a1aa0b8-4b58-4725-8e36-f83567b8ecb7.png)
