### ISSUE TITLE
Inconsistent behavior between image and text

### ISSUE THREAD

**Issue by donghaoren** [Microsoft/charticulator#97]
The image mark is on the radial layout while the text mark is not.

![image](https://user-images.githubusercontent.com/9288805/46385538-70bf7600-c671-11e8-9d99-3750256b09ea.png)

_Originally posted by @bongshin in https://github.com/Microsoft/charticulator/pull/83#issuecomment-426484206_

**Comment by donghaoren** [comment]
@bongshin -- yes, it's weird. Currently, text is a point-anchored element, image is a rectangle (rectangle = wedge in polar coordinates)-shaped element. These two types have intrinsically different behaviors that manifest in non-Cartesian coordinates.

The way to make them consistent is to add a rectangle-shaped text (which we had before but removed later) and a point-anchored image. I didn't do that because people may confuse which one to use.

I'd vote for adding a dropdown to allow choosing what anchor type to use for text and images (similar to the one for rect, ellipse, and triangle). What's your suggestion?

**Comment by bongshin** [comment]
@donghaoren -- You explained this to me before. But, the image you added to https://github.com/Microsoft/charticulator/pull/83#issue-218712894 looked ok. So, I thought it was implemented already. Let's discuss this offline.
