### ISSUE TITLE
Adding a scaffold to an axis breaks PBI and Template export

### ISSUE THREAD

**Issue by snapperlux** [Microsoft/charticulator#98]
![screenshot 313](https://user-images.githubusercontent.com/43861167/46495464-55b44980-c7ca-11e8-83ff-64efe8cb84c2.png)

**Comment by stopyoukid** [comment]
Would you kindly provide detailed reproduction steps?

**Comment by donghaoren** [comment]
@stopyoukid you can reproduce this by:
1. Drag the horizontal scaffold icon into the plot segment
2. Go to the export panel and select "Power BI Custom Visual"
