### ISSUE TITLE
Export Template Error

### ISSUE THREAD

**Issue by PBI-David** [microsoft/charticulator#990]
When trying to export a template, the message below is displayed. Which tenant setting is this referring to exactly. I'm a PBI Admin and have checked all the settings but cannot find out which relates to this specific point. Can the message be made clearer?

![image](https://user-images.githubusercontent.com/86846675/168996702-1d2fc6eb-c375-46e7-ac35-ed851d1eeb3e.png)

**Comment by zBritva** [comment]
[There is video from Power BI Tips](https://www.youtube.com/watch?v=SPV2EIWlyJs)

**Comment by PBI-David** [comment]
Thanks. That didn't work for me (even when signing out completely). I'll see if I can find a workaround.
